ooni/probe-engine

- measurementkit/task_cgo.go
Since openobservatory/mk-alpine:20190616, we use all the static
libraries that Alpine can provide us and only recompile MK.
Companion of https://github.com/measurement-kit/script-build-linux/pull/7
Xref: https://github.com/ooni/probe-cli/pull/46#issuecomment-502439944
> fix(measurementkit/task_cgo.go): build again on Alpine

- cmd/miniooni/main.go
- orchestra/testlists/testlists.go
- orchestra/testlists/testlists_test.go
This is useful so that we can better configure the testing targets.
It's especially important since now the backend will return the full test list by default.
> Add support for passing the limit and category code to the testlists pkg

- session/session.go
Needed by the probe-cli. I'm trying to reduce the coupling between internals of this repo and the probe-cli, so I am adding a session method to get the ASN as an integer, rather than continuing to assume that the probe-cli can access whatever package in here. I look forward for the cli to be able to use mainly the session and a few other packages possibly.
> session: expose the ProbeASN as an integer

- cmd/miniooni/main.go
- experiment.go
- experiment/dash/dash_cgo_test.go
- experiment/dash/dash_otherwise_test.go
- experiment/example/example.go
- experiment/example/example_test.go
- experiment/experiment_test.go
- experiment/fbmessenger/fbmessenger_test.go
- experiment/hhfm/hhfm_test.go
- experiment/hirl/hirl_test.go
- experiment/mkevent/mkevent_test.go
- experiment/mkhelper/mkhelper_test.go
- experiment/mkrunner/mkrunner_test.go
- experiment/ndt/ndt_test.go
- experiment/ndt7/ndt7_test.go
- experiment/psiphon/common.go
- experiment/psiphon/psiphon_otherwise.go
- experiment/psiphon/psiphon_test.go
- experiment/telegram/telegram_test.go
- experiment/web_connectivity/web_connectivity_test.go
- experiment/whatsapp/whatsapp_test.go
- experiment_test.go
- orchestra/testlists/testlists_test.go
- session.go
- session/session.go
- session/session_test.go
- session_test.go
- testlists.go
- testlists_test.go
This API allows to manipulate all engine things with very few structs. Also, this API introduces the possibility of querying test options and setting them rather easily.
Also, this API is very tailored to the needs of ooni/probe-cli and anticipates future usage on mobile by trying to expose something that should be easily mockable with go mobile.
> Write more abstract and powerful API

- httpx/jsonapi/jsonapi.go
- internal/orchestra/login/login_test.go
- internal/orchestra/register/register_test.go
- internal/orchestra/testorchestra/testorchestra.go
- internal/orchestra/update/update.go
- internal/orchestra/update/update_test.go
We're getting closer to #148 because now we're able to call
an authenticated API successfully.
While there, avoid code duplication in tests.
> orchestra: implement the authenticated update API

- internal/orchestra/testlists/urls/urls.go
- internal/orchestra/testlists/urls/urls_test.go
Make sure the code style and structure is consistent among all the
orchestra building blocks by always returning a pointer.
> orchestra/testlists/urls consistent w/ other orchestra

- internal/orchestra/metadata/metadata.go
- internal/orchestra/metadata/metadata_test.go
Follows closely the algorithm implemented by MK:
https://github.com/measurement-kit/measurement-kit/blob/ba98a20731a747ffb32e19991824c56a32f763a2/src/libmeasurement_kit/ooni/orchestrate_impl.hpp#L100
This is part of #148
> orchestra: implement metadata validation

- internal/orchestra/login/login.go
- internal/orchestra/statefile/statefile.go
- internal/orchestra/statefile/statefile_test.go
- internal/orchestra/testorchestra/testorchestra.go
For now we only use an in memory statefile, but it's clear that
later we'll need to persist it on disk to keep information required
to register and log-in with the OONI orchestra.
Part of #148.
> orchestra: introduce the statefile

- internal/orchestra/metadata/metadata.go
Forgot to commit yesterday. Part of #148.
> fix(orchestra): network_type is not mandatory

- experiment/oodatamodel/oodatamodel.go
- experiment/oodatamodel/oodatamodel_test.go
Apparently, the custom JSON serialisation only works with a type and
its alias, and does not work with derived types.
This makes sense but was overlooked.
I noticed this issue while working on telegram QA (#112).
Example of broken JSON:
```JSON
"test_keys": {
"requests": [
{
"failure": "connection_refused",
"request": {
"body": {
"Value": ""
}
```
> oodatamodel: make sure HTTPBody is OONI-spec compliant

- experiment/psiphon/psiphon.go
Suggested by @mirokuratczyk when we discussed the experiment
in a recent chat on Slack. Closes #153.
> psiphon: include max_runtime in results

- experiment/telegram/telegram_otherwise_test.go
This should close #142. Because maps have no stable sorting in Go, we
sometimes pick the success case first. However, such case is incomplete
because it does not set the status code as 200. Therefore, we see an
error telling us that the server returned a bad status code. Initialising
the variable to 200 should be enough to fix the bug.
> telegram/test: fix flaky test due to missing status code

- .gitignore
- experiment.go
- experiment/example/example.go
- experiment/psiphon/common.go
- experiment/psiphon/psiphon.go
- experiment/psiphon/psiphon_test.go
- session/session.go
- session/session_test.go
Closes #167
While there also fix the output of the example experiment and make sure session/session.go has 100% coverage of its statements, which were both very easy changes.
> psiphon: fetch and use config from OONI orchestra

- experiment/telegram/telegram_otherwise_test.go
The previous fix in #174 was correct, but not enough. The correct fix is
to also include the Telegram Web title in the fake returned webpage.
Closes #142
> telegram: attemp again to fix flaky test

- internal/orchestra/testlists/psiphon/psiphon.go
- internal/urlpath/urlpath.go
- internal/urlpath/urlpath_test.go
Using filepath.Join leads to wrong results on Windows where the
`\` path separator is used instead of `/`.
There was only one place where we were joining paths AFAICT but
it seems better to have a simple function for that anyway.
Closes #192.
> Join urlpaths without using filepath.Join

- internal/oonitemplates/oonitemplates.go
- internal/oonitemplates/oonitemplates_test.go
This template is going to be useful to implement #2.
We are going specifically to use it to verify whether we have
bridge connectivity at the TCP/IP level.
> Implement the TCPConnect test template

- experiment/psiphon/psiphon.go
- experiment/telegram/telegram.go
- internal/oonidatamodel/oonidatamodel.go
- internal/oonidatamodel/oonidatamodel_test.go
This was not implemented up until now, but actually is better
to have it, because #2 can also ingest hostnames, and I really
would like to provide DNS info in such case.
While there add DNS info to both psiphon and telegram.
> oonidatamodel: emit DNS data model

- internal/orchestra/testlists/urls/urls.go
- testlists.go
Closes #191. Necessary to export predictable mobile API.
> testlists/urls: use int64 for limit

- experiment/psiphon/psiphon.go
- experiment/telegram/telegram.go
- internal/oonidatamodel/oonidatamodel.go
- internal/oonidatamodel/oonidatamodel_test.go
This way we pass the same argument type to all functions, which
is convenient when we have HTTP requests that are not caused by us
calling HTTPDo, e.g., when using DoH.
This is yak shaving for making #2 possible.
> oonidatamodel: always take oonitemplates.Results as input

- internal/netxlogger/netxlogger.go
When there's an error, HTTPRoundTripDone is emitted but we should
not attempt printing headers because it doesn't make sense.
This fix has been developed while working on #2.
> netxlogger: don't print response headers on error

- go.mod
- go.sum
- internal/oonitemplates/oonitemplates.go
- internal/oonitemplates/oonitemplates_test.go
We're going to need this in #2 to connect to Tor's or_port.
> oonitemplates.go: allow skipping TLS verification

- .gitignore
- experiment/experiment.go
- experiment/psiphon/psiphon.go
- experiment/psiphon/psiphon_test.go
- experiment/telegram/telegram.go
- model/model.go
This is also functional to #12. This follows up from #218. 
While there, also ignore the `.vscode` folder.
> Forward zero start time to experiments

- internal/oonitemplates/oonitemplates.go
- internal/oonitemplates/oonitemplates_test.go
We use port numbers in netx because this is a way to make sure
that we can bind together HTTP and net traces.
We use the sign to indicate TCP or UDP.
There may be value in not scrambling the ports inside netx (I am
not sure TBH), but surely it's better to avoid doing that here.
This is also part of #12.
> oonitemplates.go: sanitise conn_id

- experiment.go
- experiment/tor/tor.go
- experiment/tor/tor_test.go
- experiment_test.go
- internal/orchestra/orchestra.go
- internal/orchestra/orchestra_test.go
- internal/orchestra/testlists/tor/tor.go
- internal/orchestra/testlists/tor/tor_test.go
- model/model.go
Closes https://github.com/ooni/probe-engine/issues/226 and https://github.com/ooni/probe-engine/issues/276
> Implement the new tor experiment

- go.mod
- go.sum
https://github.com/ooni/probe-engine/issues/320
> dependencies: update bolt and goselect because of other arch support

- internal/oonitemplates/oonitemplates.go
- internal/oonitemplates/oonitemplates_test.go
The matter is better explained in the newly added code comment. I feel
okay removing the code, because that was a okay-lets-test-it piece of
code that was only useful for running such test.
A key takeaway from the investigation of this issue is that we really
want to simplify and streamline the way in which netx interacts with
the rest of the world, to avoid using channels where we can more easily
have (1) code that directly logs, if logging is the intent, and (2)
code that directly saves data, if that is the intent.
I will open an issue to document these changes more in depth. Here as
a general reflection, I'd just like to reiterate that if we were using
less complex/general channel based patterns, we would be reducing the
odds that we see some unexpected behaviour like in this case. …
> oonitemplates: remove code causing crash on x86/arm64

- oonimkall/chanlogger.go
- oonimkall/runner.go
- oonimkall/runner_test.go
- oonimkall/settings.go
We were too strict and this means coding the Android app to
support MK and probe-engine at the same time is painful.
This is part of https://github.com/measurement-kit/measurement-kit/issues/1913.
> oonimkall: be liberal in the settings we accept

- .github/workflows/mk.yml
- measurementkit/mkcgo/mkcgo.go
Closes https://github.com/ooni/probe-engine/issues/315
> mkcgo: fail if we don't have the right MK version

- .github/workflows/mk.yml
- measurementkit/mkcgo/mkcgo.go
Also part of https://github.com/ooni/probe-engine/issues/334
> Require and use measurement-kit v0.10.11

- experiment/psiphon/psiphon_test.go
- session/session.go
- session/session_test.go
When registering, we don't need to lookup the country and the ASN. Desktop
clients only use orchestra to fetch targets for tor and psiphon. Also there
is no push notifications on desktop. Thus, it seems to me there is really
no point in doing an extra CC and ASN lookup in this code. We may need to add
a special case for mobile later, but this seems to me the best default.
This is part of the QA for https://github.com/ooni/probe/issues/1028.
> orchestra: register desktop clients with AS0 and ZZ

- cmd/miniooni/main.go
- experiment/mktesting/mktesting.go
- experiment_test.go
- oonimkall/runner.go
- session.go
- session_test.go
- testlists_test.go
Part of https://github.com/ooni/probe-engine/issues/302
This is marked API CHANGE because now consumers must call sess.Close.
> [API CHANGE] session.go: ensure we close idle connections

- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
Avoids requesting several times in a row for the control SNI, which
is frankly a waste of time when checkoing multiple inputs.
While there, make sure we never use ps.ooni.io as the helper. A bunch
of places in tests were still using it, which is generally fine but
being consistent is most likely gonna be better.
Part of https://github.com/ooni/probe-engine/issues/309.
> sniblocking: cache recent results

- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
- internal/oonidatamodel/oonidatamodel_test.go
- internal/oonitemplates/oonitemplates_test.go
- netx/http_test.go
- netx/internal/dialer/dnsdialer/dnsdialer_test.go
- netx/internal/errwrapper/errwrapper.go
- netx/internal/errwrapper/errwrapper_test.go
- netx/internal/resolver/parentresolver/parentresolver_test.go
- netx/internal/resolver/resolver_test.go
- netx/modelx/modelx.go
Since in OONI we typically use a three class system (i.e. accessible,
anomaly, or blocking), I am using these three classes.
I am also adding further information that help in understanding what
is the real root cause of the failure.
Part of https://github.com/ooni/probe-engine/issues/309.
Before merging:
> sniblocking: classify failures to produce a result

- experiment/tor/tor.go
- experiment/tor/tor_test.go
Closes https://github.com/ooni/probe-engine/issues/288
While there, I figured it made sense to add one extra test to make sure
we can gracefully handle the case where the orchestra API gives us no
targets.
> tor: use targets-list-length dependent timeout

- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
Part of https://github.com/ooni/probe-engine/issues/309
This is the result of a two hours brainstorming and pair
programming session with @fortuna, where we reviewed existing
codebase, and design, and we spelled out a classification
taxonomy more oriented towards communicating with a OONI user.
> sniblocking: revamp classification mechanism

- internal/mlablocate/mlablocate.go
- internal/mlablocate/mlablocate_test.go
I am going to reimplement a bunch of functionality for which we were
using mlab code up until now, because this reduces the amount of
coordination and discussion required to have specific functionality
that we care about here in OONI, so everyone is happier.
Part of https://github.com/ooni/probe/issues/969
> internal: add mlabns/mlablocate client

- experiment/psiphon/psiphon_test.go
- experiment/telegram/telegram_test.go
- experiment/tor/tor_test.go
- experiment_test.go
While there, cleanup code that was not used inside of a bunch
of unit tests, spotted while working on this diff.
Part of https://github.com/ooni/probe/issues/969
> experiment_test.go: run ndt7 integration test

- experiment/ndt7/callback.go
- experiment/ndt7/callback_test.go
- experiment/ndt7/dial.go
- experiment/ndt7/dial_test.go
- experiment/ndt7/download.go
- experiment/ndt7/download_test.go
- experiment/ndt7/mockable.go
- experiment/ndt7/mockable_test.go
- experiment/ndt7/ndt7.go
- experiment/ndt7/ndt7_test.go
- experiment/ndt7/param.go
- experiment/ndt7/upload.go
- experiment/ndt7/upload_test.go
- go.mod
The protocol is simple enough that we can afford that. This reduces the
coupling between our codebase and the official ndt7 client.
The only point of contact of the two codebases is the specification of
the messages that are sent by the server, which is wise to reuse.
Part of https://github.com/ooni/probe/issues/969.
> Write our own implementation of ndt7

- oonimkall/runner.go
- oonimkall/task_test.go
Allow us to count bytes consumed and to see progress from the experiment.
Closes https://github.com/ooni/probe-engine/issues/353
> runner: set experiment callbacks

- atomicx/atomicx.go
- atomicx/atomicx_test.go
- experiment/telegram/telegram.go
- experiment/tor/tor.go
- experiment/tor/tor_test.go
- internal/oonitemplates/oonitemplates.go
- internal/oonitemplates/oonitemplates_test.go
- netx/internal/dialid/dialid.go
- netx/internal/httptransport/tracetripper/tracetripper.go
- netx/internal/httptransport/tracetripper/tracetripper_test.go
- netx/internal/resolver/brokenresolver/brokenresolver.go
- netx/internal/resolver/ooniresolver/ooniresolver.go
- netx/internal/resolver/ooniresolver/ooniresolver_test.go
- netx/internal/resolver/parentresolver/parentresolver.go
- netx/internal/transactionid/transactionid.go
- netx/resolver_test.go
- oonimkall/eventemitter.go
- oonimkall/eventemitter_test.go
- oonimkall/task.go
- session.go
- session_internal_test.go
The atomicx package is less efficient however it completely avoids
using atomic semantics on int64, which may lead to crash if the
variable we are accessing is not properly aligned.
See https://golang.org/pkg/sync/atomic/#pkg-note-BUG, which reads:
> On x86-32, the 64-bit functions use instructions unavailable
> before the Pentium MMX.
>
> On non-Linux ARM, the 64-bit functions use instructions
> unavailable before the ARMv6k core.
>
> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility
> to arrange for 64-bit alignment of 64-bit words accessed atomically. The
> first word in a variable or in an allocated struct, array, or slice can
> be relied upon to be 64-bit aligned.
By using a separate package we are able to possibly even change the
way in which we implement the code, …
> Replace the atomic package with atomicx

- experiment.go
- experiment/ndt5/ndt5.go
- experiment/ndt5/ndt5_test.go
- experiment/ndt7/ndt7.go
- experiment/ndt7/ndt7_test.go
- experiment_test.go
Since now, if you request for ndt, we will give you ndt7 rather than
ndt5. You can still get ndt5 if you explicitly ask for that.
Significantly bump the version number used by ndt7 such that we leave
some room to grow MK's ndt5 implementation, just in case.
Part of https://github.com/ooni/backend/issues/369.
> Now ndt is an alias for ndt7, introduce ndt5

- atomicx/atomicx.go
- atomicx/atomicx_test.go
- cmd/miniooni/main.go
- experiment.go
- experiment/handler/handler.go
- model/model.go
- session.go
Experiments still report the bytes sent and received by them. Session
has the whole view and knows both about tests and all the other interactions
that occur as part of the session itself.
When doing this, I stumbled upon issues that I've documented:
1. https://github.com/ooni/probe-engine/issues/416
2. https://github.com/ooni/probe-engine/issues/417
They will be addressed soon.
> Session now accounts for bytes sent and received

- publish-android.bash
This is related to https://github.com/ooni/probe-engine/issues/376, which actually can already be closed, it seems, because now I'm able to fetch the AAR package from bintray.
> publish-android.bash: use more readable version number

- oonimkall/runner.go
- oonimkall/runner_test.go
- oonimkall/settings.go
Everything that does not matter to the OONI mobile app has not been
implemented and is explicitly rejected. We may add support for several
other options if there is demand, of course.
Closes https://github.com/ooni/probe-engine/issues/352
Closes https://github.com/ooni/probe-engine/issues/349
> Reject all MK settings we don't support

- .github/workflows/android.yml
We are not changing the external API dramatically and we would like the
snapshots published at bintray to only be using master.
Because breaking Go mobile is difficult, this seems okay.
We could do something more complex, but I am happy with the fact that
it's possible to use the latest snapshot of master.
We already have lots of CI in place, so doing that seems okay.
Part of https://github.com/ooni/probe-engine/issues/376.
> Android workflow only runs on the master branch

- netx/dialer/dialerbase.go
- netx/dialer/dialerbase_test.go
- netx/dialer/dnsdialer.go
- netx/dialer/tlsdialer_test.go
This allows me in the next commits to split dialerbase in a bunch of
smaller and much more independent decorators.
> netx/dialer: reduce coupling between dnsdialer and dialerbase

- netx/dialer/tls.go
- netx/dialer/tls_test.go
When we construct a TLS dialer in netx/dialer.go we're already setting up
everything such that there is a connect timeout.
No need to do that twice.
Yak shaving for https://github.com/ooni/probe-engine/issues/125.
> netx/dialer: remove unnecessary TLSDialer timeout

- netx/dialer/tls.go
This was of computing the ConnID does not assume that we know for sure
the underlying connection is a MeasuringConn.
Part https://github.com/ooni/probe-engine/issues/125.
> netx/dialer/tls.go: better way of computing ConnID

- netx/dialer.go
- netx/dialer/base.go
- netx/dialer/base_test.go
- netx/dialer/dns.go
- netx/dialer/dns_test.go
- netx/dialer/tls.go
- netx/dialer/tls_test.go
Implements the "interface defined by user" rule.
> netx/dialer: don't depend on modelx for our interfaces

- netx/dialer/base_test.go
- netx/dialer/dns_internal_test.go
- netx/dialer/dns_test.go
- netx/dialer/tls.go
- netx/dialer/tls_test.go
Like we do for the dialer. While there:
1. name the tls handshakers like the dialers
2. make tests external
> netx/dialer: separate system and timeout tls handshaker

- netx/dialer/dns.go
- netx/dialer/dns_test.go
This ensures we're using the correct string.
Spotted when working on https://github.com/ooni/probe-engine/issues/125
> fix(netx/dialer/dns.go): use unknown_failure not unknown_error

- .github/workflows/android.yml
- README.md
This strategy is like the one adopted by Psiphon where they have
a staging branch into which they merge master. Such branch is tracking
the moments in time when the client is reasonably stable.
Likewise, we'll do the same for mobile. Our master branch is anyway
generally stable, because we're already doing CI and we're going
to improve upon that in the future.
Closes https://github.com/ooni/probe-engine/issues/376
> Only build for Android from the mobile-staging branch

- netx/dialer/base.go
- netx/dialer/base_test.go
- netx/dialer/dns.go
- netx/dialer/tls.go
Usually ErrSomething is the name of an error. So use the ErrorWrapper
prefix rather than ErrWrapper to avoid any confusion.
Part of https://github.com/ooni/probe-engine/issues/125.
> refactor(netx/dialer): don't name non-errors ErrSomething

- cmd/miniooni/main.go
- experiment.go
- experiment/example/example.go
- experiment/ndt7/dial.go
- experiment/psiphon/psiphon.go
- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
- experiment/telegram/telegram.go
- experiment/tor/tor.go
- experiment/tor/tor_test.go
- experiment_test.go
- internal/oonitemplates/oonitemplates.go
- session.go
Luckily the mechanism for registering a byte counter with the context is
idempotent, so it does not matter a great deal if by mistake we, say, register
twice the experiment. In fact, there is one slot for the experiment and one
slot for the session, so it's difficult to make big mistakes in the code.
The worst that can happen is that we forget about registering in some cases
but double registrations are generally okay as long as the proper slot - for
the experiment or the session - is picked up.
Also, the places where we need to modify the context are few, so it seems
this is not going to be a very big burden. It's true that we need to remember
to use the proper dialer, but that's anyway a problem for all tests, to be
sure that we configure dialing correctly.
So, "burn the ships" like …
> Experiments in Go now use contex to report bytes usage

- netx/modelx/modelx.go
- netx/resolver/chain.go
- netx/resolver/dnsoverhttps.go
- netx/resolver/dnsovertcp.go
- netx/resolver/dnsovertcp_test.go
- netx/resolver/dnsoverudp.go
- netx/resolver/ooni.go
- netx/resolver/ooni_test.go
- netx/resolver/parent.go
- netx/resolver/resolver.go
- netx/resolver/resolver_test.go
- netx/resolver/system.go
- netx/resolver/system_test.go
If it needs an interface, let it declare that.
> refactor: let netx/resolver not depend on external interfaces

- netx/resolver/decoder_test.go
- netx/resolver/emittingtransport.go
- netx/resolver/emittingtransport_test.go
- netx/resolver/encoder.go
- netx/resolver/encoder_test.go
- netx/resolver/errorwrapper_test.go
- netx/resolver/faketransport_test.go
- netx/resolver/genreply_test.go
- netx/resolver/savinghandler_test.go
Part of https://github.com/ooni/probe-engine/issues/359. These changes should allow me to really split the OONI resolver in smaller composable pieces.
> refactor(netx): develop more basic building blocks

- netx/resolver.go
- netx/resolver/bogon.go
- netx/resolver/chain.go
- netx/resolver/chain_test.go
- netx/resolver/decoder.go
- netx/resolver/dnsoverhttps.go
- netx/resolver/dnsovertcp.go
- netx/resolver/dnsoverudp.go
- netx/resolver/emitter.go
- netx/resolver/emitter_test.go
- netx/resolver/errorwrapper.go
- netx/resolver/mockable.go
- netx/resolver/ooni.go
- netx/resolver/ooni_test.go
- netx/resolver/resolver.go
- netx/resolver/savinghandler_test.go
- netx/resolver/tls_test.go
> netx/resolver: reduce pointer receivers, curate docs and naming

- netx/resolver.go
- netx/resolver/bogon.go
- netx/resolver/bogon_test.go
- netx/resolver/chain.go
- netx/resolver/chain_test.go
- netx/resolver/decoder.go
- netx/resolver/dnsoverhttps.go
- netx/resolver/dnsovertcp.go
- netx/resolver/dnsoverudp.go
- netx/resolver/emitter.go
- netx/resolver/emitter_test.go
- netx/resolver/encoder.go
- netx/resolver/errorwrapper.go
- netx/resolver/errorwrapper_test.go
- netx/resolver/mockable.go
- netx/resolver/parent_test.go
- netx/resolver/resolver.go
- netx/resolver/serial.go
- netx/resolver/serial_test.go
- netx/resolver/system.go
- netx/resolver/system_test.go
> netx/resolver: improve naming and enforce interface conformance 

- netx/dialer/dns.go
- netx/dialer/dns_test.go
- netx/modelx/modelx.go
Let's try and use the context as little as possible as said
in https://github.com/ooni/probe-engine/issues/359
> netx/dialer: don't allow diverting lookup host

- netx/dialer.go
- netx/dialer/bytecounter.go
- netx/dialer/bytecounter_test.go
- netx/dialer/dns.go
- netx/dialer/emitter.go
- netx/dialer/errorwrapper.go
- netx/dialer/integration_test.go
- netx/dialer/timeout.go
- netx/dialer/tls.go
- move policy to netx/dialer.go (i.e. down one level)
- improve documentation
- make integration tests skippable
> netx/dialer: finish refactoring

- netx/http.go
- netx/oldhttptransport/bodytracer.go
- netx/oldhttptransport/bodytracer_test.go
- netx/oldhttptransport/httptransport.go
- netx/oldhttptransport/httptransport_test.go
- netx/oldhttptransport/tracetripper.go
- netx/oldhttptransport/tracetripper_test.go
- netx/oldhttptransport/transactioner.go
- netx/oldhttptransport/transactioner_test.go
The existing transport mechanism is working but it's relying too much
on the context, which is not what we said we wanted to do next in
https://github.com/ooni/probe-engine/issues/359. While it was relatively
quick and easy to refactor resolver and dialer, it seems more long and
complicated to wrestle with the transport.
Hence, the choice to rename the existing transport `oldtransport` and
to start afresh using different design principles.
Existing code should continue of work.
Part of https://github.com/ooni/probe-engine/issues/359.
> rename(netx): httptransport => oldhttptransport

- netx/dialer/integration_test.go
- netx/dialer/logging.go
- netx/dialer/logging_test.go
- netx/resolver/integration_test.go
- netx/resolver/logging.go
- netx/resolver/logging_test.go
One of the main points of https://github.com/ooni/probe-engine/issues/359
is that we should be logging independently of emitting events.
Let's start doing that of netx/{dialer,resolver}.
Part of https://github.com/ooni/probe-engine/issues/359.
> netx/{dialer,resolver}: introduce independent logger

- cmd/miniooni/main.go
- experiment.go
- measurementkit/measurementkit.go
- netx/bytecounter/bytecounter.go
- netx/bytecounter/bytecounter_test.go
- netx/dialer/bytecounter.go
- netx/dialer/bytecounter_test.go
- netx/httptransport/bytecounter.go
- netx/httptransport/bytecounter_test.go
- netx/httptransport/httptransport.go
- netx/httptransport/integration_test.go
- netx/httptransport/logging.go
- netx/httptransport/logging_test.go
- netx/httptransport/mockable_test.go
- netx/httptransport/system.go
- netx/httptransport/useragent.go
- netx/httptransport/useragent_test.go
- oonimkall/runner.go
- session.go
This httptransport does not use the context at all, features logging and
bytecounting functionality, and uses existing dialers, resolvers.
This is part of:
1. https://github.com/ooni/probe-engine/issues/359
2. https://github.com/ooni/probe-engine/issues/125
This diff also needs to consolidate a single byte counter implementation
because we probably want to keep the older byte counting for the experiments.
This diff also renames KiBs to KibiBytes, which is more obvious.
> netx: write new, simpler httptransport

- netx/httptransport/bytecounter.go
- netx/httptransport/bytecounter_test.go
This seems to happen very often. Add also a test to catch regressions.
Part of https://github.com/ooni/probe-engine/issues/125.
> netx/httptransport/bytecounter: deal with N>0,io.EOF result

- experiment.go
- netx/httptransport/system.go
- session.go
- testlists.go
This allows us to count bytes (https://github.com/ooni/probe-engine/issues/125)
and is in line with netx simplification (https://github.com/ooni/probe-engine/issues/359).
> engine: use the new httptransport

- experiment/ndt7/ndt7.go
Occurred to me when working on https://github.com/ooni/probe-engine/issues/259
> ndt7: explicit protocol and no useless warnings

- .github/workflows/golang.yml
- measurementkit/mkcgo/mkcgo.go
This seems more consistent. Making mkcgo conditional on CGO is
a relic of when one needed to disable CGO to disable MK.
Spotted when working on something else.
> Don't build mkcgo with `-tags nomk`

- experiment.go
This is wrong because there may be persistent connection that we
may be missing. For this reason, we count at HTTP level.
Closes https://github.com/ooni/probe-engine/issues/484
> SubmitAndUpdateMeasurements: don't count bytes using context

- experiment/dash/client.go
- experiment/dash/dash.go
- experiment_test.go
- netx/httptransport/system_compat.go
It should be noted that this solution is such that byte counting
does not work when using HTTP for Go < 1.14.
> dash: make sure we correctly count bytes

- experiment/dash/dash.go
- experiment/dash/dash_test.go
- experiment/dash/model.go
- experiment/dash/nologger.go
- experiment/dash/spec.go
As part of merging the existing codebase with the neubot/dash client, let's
also dispose of the code that does not matter much.
For example, remove server-side code only that slipped through when we
merged neubot/dash client into this codebase.
Also, there was code whose only purpose was printing serialized JSONs in
debug mode, which we actually don't need.
> dash: remove unused/unimportant code

- experiment/dash/client.go
- experiment/dash/dash.go
- experiment/dash/dash_test.go
This is similar to ndt7. Treat this kind of errors more
liberally and do not fail the whole experiment.
Zap code to obtain the server measurements since we aren't
currently using them.
> dash: don't report error after download started

- experiment/dash/dash.go
- experiment/dash/dash_test.go
The implementation has changed significantly.
> dash: bump the version number

- experiment/dash/dash.go
- experiment/dash/dash_test.go
- experiment/handler/handler.go
- experiment/ndt7/dial.go
- experiment/ndt7/dial_test.go
- experiment/ndt7/ndt7.go
- experiment/ndt7/ndt7_test.go
- internal/mlablocate/mlablocate.go
- internal/mlablocate/mlablocate_test.go
- internal/mockable/mockable.go
- model/model.go
- netx/dialer/logging.go
- netx/dialer/proxy.go
- netx/dialer/proxy_internal_test.go
- netx/dialer/proxy_test.go
- netx/httptransport/httptransport.go
- netx/httptransport/system.go
- netx/httptransport/system_compat.go
- session.go
- session_test.go
The rationale of this change is the following:
1. honouring `HTTP_PROX`Y is increasingly weird when we have HTTP and non-HTTP pieces of code
2. so, let's instead introduce a concept of explicit proxy at SOCKS5 level
3. if we have a concept of explicit proxy, then use it for everything, to honour the user wishes
4. then we don't need a transport without proxy anymore
Part of https://github.com/ooni/probe-engine/issues/506
> Rework code that manages proxying

- cmd/miniooni/main.go
- experiment/dash/dash.go
- experiment/dash/dash_test.go
- experiment/ndt7/dial.go
- experiment/ndt7/dial_test.go
- experiment/ndt7/ndt7.go
- experiment/ndt7/ndt7_test.go
- experiment/psiphon/psiphon.go
- internal/mockable/mockable.go
- internal/psiphonx/psiphonx.go
- internal/psiphonx/psiphonx_test.go
- model/model.go
- model/model_test.go
- netx/httptransport/httptransport.go
- netx/httptransport/integration_test.go
- session.go
- session_test.go
The design is that we have a tunnel managed by the session. We may ask the
session to possibly start a tunnel, provided that one is configured.
If no tunnel is configured, nothing actually happens. Otherwise, we get
a proxy (similar to when `--proxy` is used) that we use.
The psiphon experiment now needs refactoring to use this tunnel.
Part of https://github.com/ooni/probe-engine/issues/506.
> ndt7 and dash can run over psiphon

- experiment.go
- model/model.go
This is non standard. We don't need to add it to the spec. It is just
useful when you are vetting measurements manually.
Cherry-picked from work related to https://github.com/ooni/probe-engine/issues/509
> Measurement += ProbeNetworkName non standard field

- netx/httptransport/httptransport.go
- netx/httptransport/integration_test.go
- netx/resolver/cache.go
- netx/resolver/cache_test.go
There is no cache aging. If a resolution is successful, then we
do cache the result. This is meant as a mechanism to make measurements
faster and with less data points. For this reason it's disabled by
default. Consider for example the case where `http://www.example.com`
redirects you to `https://www.example.com`. You really don't want
to perform the name resolution again in this case.
As a side note, depending on the resolver we're using, we may not
need the caching mechanism. Nonetheless, using the cache always when
measuring also reduces the number of duplicate entries we produce
where only the first entry has actually been resolved.
This was developed as part of https://github.com/ooni/probe-engine/issues/509
> Introduce a caching DNS resolver

- experiment/ndt7/dial.go
- netx/httptransport/httptransport.go
- netx/resolver.go
- netx/resolver/chain.go
- netx/resolver/chain_test.go
- netx/resolver/fake_test.go
- netx/resolver/resolver.go
- netx/resolver/saver.go
- netx/resolver/serial.go
- netx/resolver/serial_test.go
- netx/resolver/system.go
- netx/resolver/system_test.go
- netx/resolver_internal_test.go
- netx/resolver_test.go
These are useful bits of information when filling a measurement
because they allow us to understand what transport is used.
Part of https://github.com/ooni/probe-engine/issues/509
> resolver: collect transport's Network and Address

- netx/httptransport/saver.go
- netx/httptransport/saver_test.go
Bugfix developed as part of https://github.com/ooni/probe-engine/issues/509
While there, implement a unit test
> httptransport: don't save events twice

- netx/dialer/saver.go
- netx/dialer/saver_test.go
- netx/httptransport/httptransport.go
- netx/httptransport/integration_test.go
We may want to perform TLS measurements without saving R/W events and we may
want to save R/W events without performing TLS.
We also may want to perform dial measurements without saving R/W events and we
may want to save R/W events without dial measurements.
So, create a new dialer that also does R/W measurements.
Also, add option to httptransport.New factory to enable this functionality.
> netx: decouple TLS from saving R/W events

- netx/httptransport/saver.go
- netx/httptransport/saver_test.go
Using http/httptrace leads to tricky code because of the context and the
fact we may mistakenly register more than once.
If we want, we have network level data. So we are going to use network
level data to evaluate performance instead.
> netx/httptransport: stop using http/httptrace

- netx/httptransport/httptransport.go
- netx/httptransport/saver.go
- netx/httptransport/saver_test.go
In https://github.com/ooni/probe-engine/pull/556 I was optimistic. It seems
it's difficult to generate a HAR w/o using http/httptrace.
Thus, reimplement measuring using http/httptrace. This time, however, do that
in a separate round tripper, to be more tidy.
> netx/httptransport: reintroduce http/httptrace

- experiment/dash/dash.go
- netx/httptransport/httptransport.go
- netx/httptransport/integration_test.go
Specifically for DASH, we're only interested in saving dials.
> netx/httptransport: allow to configure different savers

- netx/httptransport/httptransport.go
- netx/httptransport/saver.go
- netx/httptransport/saver_test.go
- netx/trace/event.go
Merged also into https://github.com/ooni/probe-engine/pull/529
> netx: restructure http events for easy saving in OONI format

- netx/internal/errwrapper/errwrapper.go
- netx/internal/errwrapper/errwrapper_test.go
- netx/internal/errwrapper/sanitizer.go
- netx/internal/errwrapper/sanitizer_test.go
To this end, vendor code from keroserene/snoflake with attribution.
Closes https://github.com/ooni/probe-engine/issues/546
> netx/internal/errwrapper: scrub IP addresses from errors

- experiment.go
- experiment/urlgetter/configurer.go
- experiment/urlgetter/configurer_test.go
- experiment/urlgetter/getter.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/runner.go
- experiment/urlgetter/runner_test.go
- experiment/urlgetter/urlgetter.go
- experiment/urlgetter/urlgetter_test.go
This is the basic building block on which to rewrite most other OONI
experiments. It handles different kind of URLs, leading to performing
HTTP requests, TCP connects, TLS handshakes, etc.
> experiment: add the new urlgetter experiment

- experiment/urlgetter/getter_test.go
- netx/archival/archival.go
- netx/archival/archival_test.go
- netx/internal/errwrapper/errwrapper.go
- netx/internal/errwrapper/sanitizer.go
- netx/internal/errwrapper/sanitizer_test.go
This is related to https://github.com/ooni/probe-engine/issues/290, which is
not done, because we're still using old netx in some places.
> netx: reduce toplevel HTTP errors to OONI failures

- experiment/urlgetter/configurer.go
- experiment/urlgetter/configurer_test.go
- experiment/urlgetter/urlgetter.go
- netx/archival/archival.go
- netx/archival/archival_test.go
- netx/dialer/saver.go
- netx/dialer/saver_test.go
- netx/httptransport/httptransport.go
- netx/httptransport/httptransport_test.go
- netx/trace/event.go
> netx, experiment/urlgetter: allow to disable TLS verify

- experiment/urlgetter/configurer.go
- experiment/urlgetter/configurer_test.go
- experiment/urlgetter/urlgetter.go
- netx/httptransport/httptransport.go
- netx/httptransport/httptransport_test.go
- netx/resolver/cache.go
- netx/resolver/cache_test.go
Seems to be required when running HTTP experiments where we have
previously already resolved the domain(s) we need.
> netx, experiment: implement prefilled DNS cache

- netx/httptransport/httptransport.go
- netx/httptransport/httptransport_test.go
- netx/resolver/address.go
- netx/resolver/address_test.go
We want to map an IP address to itself rather than failing.
Part of https://github.com/ooni/probe-engine/issues/543.
> netx: introduce resolver that handles IP addresses

- experiment/urlgetter/urlgetter.go
- experiment/urlgetter/urlgetter_test.go
This simplifies analysing the measurement JSON.
> experiment/urlgetter: include DNSCache in TestKeys

- netx/archival/archival.go
- netx/archival/archival_test.go
Part of https://github.com/ooni/probe-engine/issues/547
> fix(netx/archival): include TLS server name

- experiment.go
- experiment/psiphon/psiphon.go
- experiment/psiphon/psiphon_test.go
- experiment/urlgetter/getter.go
- experiment/urlgetter/urlgetter.go
- experiment_test.go
- libminiooni/libminiooni.go
- oonimkall/runner.go
This diff contains the following changes:
1. rewrite psiphon to use the urlgetter experiment
2. hence, get for free performance metrics
3. modify the code such that you can say that an experiment knows
how to handle input but does not require input
4. declare that psiphon is such an experiment
If we want to pass specific URLs with psiphon, this is a matter of
policy in the ooni/probe-cli tool. Nothing more to do here.
Closes https://github.com/ooni/probe-engine/issues/404.
> psiphon: collect performance metrics from arbitrary URLs

- experiment.go
- experiment/mkhelper/mkhelper_test.go
- probeservices/bouncer.go
- probeservices/bouncer_test.go
- probeservices/collector.go
- probeservices/collector_test.go
- session.go
To implement https://github.com/ooni/probe/issues/887, it helps to have all the
logic for speaking with probeservices in the same place.
> refactor: merge bouncer and collector into probeservices

- netx/dialer/proxy.go
- netx/dialer/proxy_test.go
This diff allows us to use the context in order to setup an extemporary
proxy that is only valid within the context of the context.
While working on https://github.com/ooni/probe/issues/887, I have
determined that this is beneficial to switching over to using a
psiphon tunnel, where everything else fails.
While this is a bit of a hack, and I was not convinced about continuing to use the
context in this way previously, not using the context seems to required lots of
burden because we need to setup and manage an alternative HTTP client.
> netx/dialer/proxy.go: allow extemporary proxy

- internal/jsonapi/jsonapi.go
- internal/jsonapi/jsonapi_test.go
- probeservices/bouncer.go
- probeservices/collector.go
This diff modifies the code in jsonapi and probeservices such that it
is now possible to configure cloudfronting and tunneling.
Cloudfronting is configured by setting and propagating the Host header.
Tunneling is configured by forcing a specific proxy URL inside of
the context, using 4a39a3bce5d91c1a60d6185220cbb55079b51933.
Part of https://github.com/ooni/probe/issues/887
> jsonapi probeservices: allow cloudfronting and tunneling

- experiment.go
- internal/jsonapi/fake_test.go
- internal/jsonapi/jsonapi.go
- internal/jsonapi/jsonapi_test.go
- probeservices/bouncer.go
- probeservices/bouncer_test.go
- probeservices/collector.go
- probeservices/collector_test.go
- session.go
This PR contains a but of unrelated diffs that perform refactoring of jsonapi and probeservices. I want these changes to be in before continuing with https://github.com/ooni/probe/issues/887.
> jsonapi, probeservices: refactoring before detecting blocking

- libminiooni/libminiooni.go
- oonimkall/runner.go
- session.go
- session_test.go
This diff significantly simplifies the way in which the session
is initialized. Now all options are set as part of the session
configuration and then everything follows nicely(TM).
This means that we don't need to worry when the session is alive
whether the programmer has changed, e.g., the collector URL.
Yak shaving as part of https://github.com/ooni/probe/issues/887.
> [API CHANGE] session: significantly simplify initialization

- internal/sessionresolver/sessionresolver.go
- internal/sessionresolver/sessionresolver_test.go
- oonimkall/task_test.go
- session.go
This is useful at least as far as we're talking with OONI servers.
Closes https://github.com/ooni/probe-engine/issues/521.
Part of https://github.com/ooni/probe/issues/887.
> session: use cloudflare doh by default, system as fallback

- libminiooni/libminiooni.go
- session.go
- session_test.go
This PR contains a set of small diffs that I implemented while making sure that if we selfcensor us a lot, we can still route around that censorship using a tor tunnel. So, specifically:
1. I added the possibility of starting a tunnel to `miniooni`
2. I made sure an existing `tor` tunnel is not mistakenly interpreted as a `psiphon` tunnel and viceversa; also, in this vein, I clarified the tunnel rules with more tests
3. fixed a `miniooni` issue that prevented running `psiphon`
This work is part of https://github.com/ooni/probe/issues/887.
> More confidence that we can use tor to contact probe services

- internal/jsonapi/jsonapi.go
I felt this needed to be clarified more explicitly.
Part of https://github.com/ooni/probe/issues/887
> jsonapi: explain why every request honours the proxy, if any

- netx/httptransport/httptransport.go
- netx/httptransport/httptransport_test.go
Needed to do https://github.com/ooni/probe-engine/issues/581
Usage:
```bash
./miniooni -OResolverURL=dot://8.8.8.8:853 -i dnslookup://example.com urlgetter
./miniooni -OResolverURL=tcp://8.8.8.8:53  -i dnslookup://example.com urlgetter
```
> netx: implement the tcp:// and dot:// schemes for DNS

- experiment/urlgetter/getter.go
- geoiplookup/mmdblookup/mmdblookup.go
- geoiplookup/mmdblookup/mmdblookup_test.go
- libooniffi/ooniffi_test.go
- netx/archival/archival.go
- netx/archival/archival_test.go
- session.go
In addition to being useful for analysing data, this extra bit of information seems also super valuable when our objective is that of assessing the goodness of our ASN database.
In fact, it means we submit to ourselves annotated IP addresses. So we can use other databases to verify how good are our annotations, and whether we need to improve.
This work has been done to move forward https://github.com/ooni/probe-engine/issues/584.
While carrying out this work, I noticed and fixed two bugs, which are separate commits.
> Save ASN and ASOrgName of each DNS lookup

- model/model.go
This has been recommended by @hellais some time ago. With the
merge of this diff, we can close https://github.com/measurement-kit/measurement-kit/issues/1884.
(I didn't bother with changing with in MK, since we are decommissioning
it, and I just acted upon probe-engine.)
> model/model.go: use 127.0.0.2 for unknown resolver IP

- experiment/urlgetter/runner.go
Closes https://github.com/ooni/probe-engine/issues/572
> urlgetter: set allow-all cookiejar for HTTP requests

- internal/torx/torx.go
- libminiooni/libminiooni.go
The location of the file can always be deduced given a session. This means
we can read the logs after a tor tunnel has been used.
Closes https://github.com/ooni/probe-engine/issues/625.
> torx: save tor logs to a file in tempdir

- oonimkall/runner.go
- oonimkall/runner_test.go
- oonimkall/settings.go
- oonimkall/task_test.go
After this change, we're unable to test that the code WAIs when we
cannot discover backends and open a report.
This will be fixed once we have support for ProbeServicesBaseURL
inside of the session.go file.
Part of https://github.com/ooni/probe-engine/issues/621.
> oonimkall: remove support for {Bouncer,Collector}BaseURL

- experiment.go
- experiment_test.go
- libminiooni/libminiooni.go
- session.go
- session_internal_test.go
- session_test.go
The distinction between bouncer and collector has vanished! Now we have
probe services that we query when using the bouncer protocol and that
we later use when opening/updating/closing the report.
This is part of https://github.com/ooni/probe-engine/issues/621.
> engine: replace bouncer and collector with probe services

- oonimkall/task_test.go
It still beats me how it's possible that the test takes more than 15
seconds to complete. But maybe I don't understand the internals of how
GitHub actions run with high parallelism. Or there is something else
that is broken and I don't know for sure that it is.
Example of broken build: https://github.com/ooni/probe-engine/pull/497/checks?check_run_id=713886264
I have now rewritten this test such that it runs forever if the task
is stuck somewhere. So, this will give me more information.
Spotted while working on https://github.com/ooni/probe-engine/issues/498
> fix(task_test.go): fix test logic to avoid races

- experiment/dash/dash.go
- experiment/ndt7/ndt7.go
- experiment/urlgetter/urlgetter.go
- experiment/urlgetter/urlgetter_test.go
- netx/archival/archival.go
- netx/archival/archival_test.go
- netx/archival/archival_test_internal.go
Part of https://github.com/ooni/probe-engine/issues/533
While there, bring coverage in `netx/archival` to 100%.
> Make sure we declare the tunnel data format when needed

- netx/dialer/eof_test.go
- netx/dialer/tls.go
- netx/dialer/tls_test.go
- netx/selfcensor/selfcensor.go
- netx/selfcensor/selfcensor_test.go
This should lead to a more understandable sequence of low level events
where we don't see anymore the "use of closed network connection".
Part of https://github.com/ooni/probe-engine/issues/576.
> tls/timeout: use deadline rather than context

- experiment.go
Build otherwise broken. See: https://github.com/ooni/probe-engine/runs/720733159.
> fix(experiment.go): serialize assets version in 32bit compatible way

- internal/orchestra/orchestra.go
- internal/orchestra/testlists/urls/urls_test.go
- internal/sessionresolver/sessionresolver_test.go
- netx/dialer/dns_test.go
- netx/http_test.go
- testlists.go
Prodded by @hellais. Will give us better performance. Yet, this is just
half of the job. I need to open a follow up issue suggesting that we should
always be using the same probe service that we selected. Otherwise, some
parts of our infra will be less resilient than others.
Such follow up issue is https://github.com/ooni/probe-engine/issues/651.
> Use ps.ooni.io wherever it makes sense to do so

- experiment/urlgetter/getter.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/urlgetter.go
This was planned inside https://github.com/ooni/probe-engine/issues/656.
It actually also helps with https://github.com/ooni/probe-engine/issues/646.
> urlgetter: add tcp_connect to test_keys

- experiment/urlgetter/getter_test.go
- experiment/urlgetter/runner.go
- experiment/urlgetter/urlgetter.go
We need this to reimplement the telegram experiment in terms of
the urlgetter experiment, to simplify the code.
See https://github.com/ooni/probe-engine/issues/646.
> urlgetter: allow to configure the method

- experiment/urlgetter/multi.go
- experiment/urlgetter/multi_test.go
With the Multi urlgetter you can perform operations in parallel with a
specific degree of parallelism. You get results back as they arrive via
a channel that is returned on output.
We'll use this functionality pretty much soon to rewrite the Telegram
experiment in terms of the urlgetter experiment.
Reference issue: https://github.com/ooni/probe-engine/issues/646
> urlgetter: introduce the Multi urlgetter

- netx/archival/archival.go
- netx/archival/archival_test.go
- netx/modelx/modelx.go
This will be useful to more easily classify the cause of blocking.
This is part of https://github.com/ooni/probe-engine/issues/646
> netx/archival: extract the operation that failed

- experiment/urlgetter/getter.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/urlgetter.go
- netx/modelx/modelx.go
This is very useful to quickly understand what actually went wrong. It is
a facet of the next design that was never really used.
Also, acknowledge that, in some cases, there isn't a real failed operation
because the error happens before we enter into our network stack.
This happens, for example, when the context we're using is canceled.
To address this potential issue, introduce and use a `"top_level"` operation
that describes this specific situation.
This work is part the telegram rewrite: https://github.com/ooni/probe-engine/issues/646.
Also, with this diff landing we can close https://github.com/ooni/probe-engine/issues/311,
which mentioned oonimkall (the old implementation of netx) but is still
basically talking about the same concept we're implementing here.
> urlgetter: expose the operation that failed

- experiment/urlgetter/getter.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/urlgetter.go
- netx/archival/archival.go
We often need to check the status code of the last response in the chain
and/or to see the body of such response.
To simplify these use cases, introduce two new variables that contain such
values. These variables are not JSON serialised, because it does not make
sense for us to do that. One can always recompute these fields, and the point
of this patch is just to avoid duplicating code.
Added an extra integration test to make sure that the value of these new
variables is okay not only when the context is canceled but also when we're
not doing HTTP but something else, e.g., just TLS.
Part of https://github.com/ooni/probe-engine/issues/646.
We will use this new code to simplify post processing of Telegram results.
> urlgetter.TestKeys: add extra fields to simplify analysis

- experiment/tor/tor_test.go
- experiment/urlgetter/getter_test.go
- netx/errorx/errorx.go
- netx/errorx/errorx_test.go
- netx/modelx/modelx.go
Like for MK errors, use the same naming of the C++11 library.
This error will happen when the mobile app will interrupt specific
tests, so better to have a clear naming for it.
Part of https://github.com/ooni/probe-engine/issues/646.
> netx/errorx: wrap context.Canceled

- experiment_test.go
- geoiplookup/iplookup/avast/avast.go
- internal/httpx/fake_test.go
- internal/httpx/jsonapi.go
- internal/httpx/jsonapi_test.go
- internal/orchestra/login.go
- internal/orchestra/register.go
- internal/orchestra/tor.go
- internal/orchestra/update.go
- internal/orchestra/urls.go
- probeservices/bouncer.go
- probeservices/client.go
- probeservices/collector.go
- probeservices/collector_test.go
To merge orchestra and probeservices, I also need to merge the two
supporting packages: jsonapi and fetch.
Specifically, we need to make fetch as cool as jsonapi and support also
cloudfronted and proxying via Tor/psiphon etc.
To this end, rename jsonapi to httpx, and start renaming the methods
such that it's clear that they deal with JSON input/output.
The next step will be to merge fetch with httpx.
> rename: internal/jsonapi => internal/httpx

- internal/mockable/mockable.go
- internal/orchestra/orchestra.go
- internal/orchestra/orchestra_test.go
We're using probe-services now, so there's no need to distinguish.
> orchestra: remove distinction between registry and orchestra base URLs

- experiment/tor/tor_test.go
- internal/mockable/mockable.go
- internal/orchestra/orchestra.go
- internal/orchestra/orchestra_test.go
- session.go
- session_test.go
This should be one of the last steps. The orchestra client and the probeservices
client now have basically the same fields and the same constructor.
This means that it should be possible, in a follow-up step, to merge them.
In this diff, I am slightly reducing the code coverage. This will be amended in
a follow-up PR, once I have merged orchestra into probeservices.
> internal/orchestra: rewrite to have same constructor as probeservices

- internal/mockable/mockable.go
- libminiooni/libminiooni.go
- model/model.go
- probeservices/urls.go
- probeservices/urls_test.go
- testlists.go
I want to replace the old test-list/urls API with this new API. The main
reason for doing so is that the new API uses the OrchestraClient instance
return by the session. The nice property of such client is that it will
use the endpoint we have settled to use when doing the selection of the best
probe service. Therefore, this would allow the apps to use either the fastest
service or the right circumvention method.
As part of merging this diff, I shall also create an issue about making sure
all users of the old API are migrated to the new API, such that we can remove
the old API. For now, the old API is just marked as deprecated.
> probeservices: sketch out new API to access test lists

- probeservices/bouncer.go
- probeservices/bouncer_test.go
We have now migrated to probeservices. The probeservices implement the
bouncer API, therefore, no need to keep the bouncer API around.
Cleanup as part of https://github.com/ooni/probe-engine/issues/651.
> probeservices: remove bouncer GetCollector API

- probeservices/psiphon.go
- probeservices/tor.go
This code pattern also happens to be less error prone.
Cleanup as part of https://github.com/ooni/probe-engine/issues/651
> probeservices: tor, psiphon: use more compact code pattern

- geoiplookup/iplookup/avast/avast.go
- internal/httpx/jsonapi.go
- internal/httpx/jsonapi_test.go
- probeservices/bouncer.go
- probeservices/collector.go
- probeservices/login.go
- probeservices/register.go
- probeservices/tor.go
- probeservices/urls.go
We used to use CRUD names. Naming the method explicitly is more intuitive.
> httpx: more intuitive names for jsonapi

- internal/mockable/mockable.go
- probeservices/login_test.go
- probeservices/orchestra.go
- probeservices/psiphon_test.go
- probeservices/register_test.go
- probeservices/testorchestra/testorchestra.go
- probeservices/tor_test.go
> refactor(probeservices): move testing fixtures in subpackage

- probeservices/probeservices.go
- probeservices/statefile.go
- probeservices/statefile_test.go
The StateFile is like:
```Go
// StateFile is the orchestra state file. It is backed by
// a generic key-value store configured by the user.
type StateFile struct {
Store model.KeyValueStore
key   string
}
```
where `Store` is an interface and changes happen in `Store`.
So, we don't need to return a pointer in the constructor and we
don't need to pass around a pointer.
> refactor(probeservices): StateFile does not need to be a pointer

- experiment/tor/tor.go
- experiment/tor/tor_test.go
- internal/mockable/mockable.go
- model/model.go
- probeservices/tor.go
- probeservices/tor_test.go
- session.go
- session_test.go
1. make sure we pass `country_code=$CC` to the orchestra API https://github.com/ooni/probe-engine/issues/629
2. add functional test to ensure the output is scrubbed in such case https://github.com/ooni/probe-engine/issues/721
> experiment/tor: allow for testing private bridges

- netx/resolver/dnsoverhttps.go
- netx/resolver/dnsoverhttps_test.go
No need to announce us as being OONI.
Part of https://github.com/ooni/probe-engine/issues/716
> doh: use same user-agent used for measurements

- experiment/telegram/telegram.go
- experiment/telegram/telegram_test.go
- experiment/urlgetter/multi.go
- experiment/urlgetter/runner.go
- experiment/urlgetter/runner_test.go
- experiment/urlgetter/urlgetter.go
In some cases, we want to fail if we see an HTTP status code >= 400.
This is certainly the case when we're doing plain text HTTP.
Both the Telegram implementation and WhatsApp can benefit from that
functionality, when connecting to the web interface.
Thus, I've factored the code out of the Telegram implementation
and I have moved it inside the urlgetter package.
Part of https://github.com/ooni/probe-engine/issues/55
> urlgetter: implement FailOnHTTPError

- experiment/whatsapp/whatsapp.go
- experiment/whatsapp/whatsapp_test.go
As mentioned in the commit, we see a 400 Bad Request error from
WhatsApp when using the User-Agent we use for measurements along
with the standard Golang's ClientHello fingerprint.
This looks like MITM detection like https://mitm.watch to me.
A fix for this issue could be to find out a combination of User-Agent
and ClientHello that does not trigger 400 and keep the test as it
should according to the spec.
Yet, if there is MITM detection, it may change. This will likely
cause future false positives, and we already have a bunch of such
false positives for the IM tests.
Also, it currently seems safe to assume that, if we can perform
a TLS handshake with a certificate pool we trust, then we are
talking with WhatsApp. Therefore, the status code and the returned
web page matter much less than …
> whatsapp: implement remaining checks

- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
- experiment/urlgetter/urlgetter.go
A more substantial rewrite would have been possible. But let's proceed
piecemeal and, for now, just stop depending on the old netx.
This was the objective and we achieved it.
When we'll tackle the task of improving testing, we'll also refactor
the tests and see if we can also simplify sniblocking further.
Part of https://github.com/ooni/probe-engine/issues/684
> sniblocking: rewrite using urlgetter

- netx/archival/archival.go
- netx/archival/archival_test.go
See failing test https://github.com/ooni/probe-engine/pull/751/checks?check_run_id=853562310
Spotted as part of https://github.com/ooni/probe-engine/issues/740
> fix(net/archival): emit sorted headers

- netx/selfcensor/selfcensor.go
While there use a more clear name for this variable.
Closes https://github.com/ooni/probe-engine/issues/764
> fix(selfcensor.go): add timeout for default net.Dialer

- netx/selfcensor/selfcensor.go
This will allow HHFM to use a Dialer for which self censorship
works, which in turn enables quick testing.
Part of https://github.com/ooni/probe-engine/issues/763
> selfcensor: expose a Dialer that others can reuse

- cmd/miniooni/main.go
Makes it much more obvious that something went wrong beyond just
inspecting the exit code and noticing is nonzero.
Part of https://github.com/ooni/probe-engine/issues/763
> cmd/miniooni/main.go: print log message in case of panic

- internal/sessionresolver/sessionresolver.go
- netx/resolver/dnsoverhttps.go
- netx/selfcensor/selfcensor.go
Let us use 15 seconds as timeout for connecting. Let us give DoH 45 seconds to resolve by default. This means, if there are timeouts, we can attempt with three IP addresses. At the same time, implement something like TRR2 for the session resolver such that we fallback to using the system resolver quite quickly if DoH doesn't work.
> DoH: better timeouts and TRR2-like implementation

- experiment/webconnectivity/analyze.go
- experiment/webconnectivity/control.go
- experiment/webconnectivity/measure.go
- experiment/webconnectivity/webconnectivity.go
- internal/mockable/mockable.go
- model/model.go
This diff implements the basic machinery. We perform the measurement
and the control measurement. We'll write tests next.
For now, we still use MK for Web Connectivity. We will not switch to the
new implementation until it's feature complete and tested.
Part of https://github.com/ooni/probe-engine/issues/776.
> Rewrite Web Connectivity in Go (1/n)

- experiment/webconnectivity/analyze.go
- experiment/webconnectivity/analyze_test.go
> webconnectivity/BodyLengthChecks: handle truncated body

- experiment/webconnectivity/analyze.go
- experiment/webconnectivity/analyze_test.go
> StatusCodeMatch: rewrite to avoid using urlgetter extensions

- experiment/webconnectivity/webconnectivity.go
- experiment/webconnectivity/webconnectivity_test.go
> webconnectivity: ensure early on that input is an URL

- experiment/hhfm/hhfm.go
- experiment/tor/tor.go
- experiment/urlgetter/runner.go
- experiment/urlgetter/runner_test.go
- internal/httpheader/accept.go
- internal/httpheader/acceptlanguage.go
- internal/httpheader/useragent.go
- netx/resolver/dnsoverhttps.go
- netx/resolver/dnsoverhttps_test.go
- session.go
Life is already too complicated that adding a level of randomness here
is possibly only going to confuse TLS MITM detection.
Play it simple and use always same headers.
> internal/httpheader: stop claiming headers are random

- experiment/webconnectivity/endpoints.go
- experiment/webconnectivity/endpoints_test.go
- experiment/webconnectivity/webconnectivity.go
I'm trying to split Measure in smaller pieces.
> webconnectivity: run Control right after DNSLookup

- experiment/webconnectivity/httpanalysis.go
- experiment/webconnectivity/webconnectivity.go
While there introduce logging of HTTP analysis
> webconnectivity: simplify saving TCPConnect info

- .github/workflows/golang.yml
This allows us to check weekly whether everything is still WAI.
Closes https://github.com/ooni/probe-engine/issues/819.
> github: run golang.yml weekly

- .gitignore
- QA/.gitignore
- QA/common.py
- QA/pyrun.sh
- cmd/jafar/Dockerfile
1. make sure we run as unprivileged user in its home directory
2. share GOPATH and GOCACHE to avoid rebuilding every time
Part of https://github.com/ooni/probe-engine/issues/829
> QA: improve the implementation

- .github/workflows/qa.yml
- .gitignore
- QA/webconnectivity.py
This starts adding a single check, to check whether the framework works for Web Connectivity. More checks later.
> QA: start implementing checks for Web Connectivity

- QA/webconnectivity.py
- experiment/webconnectivity/httpanalysis.go
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
> QA(webconnectivity): make sure output matches MK

- QA/webconnectivity.py
Verified locally that we behave like MK.
Part of https://github.com/ooni/probe-engine/issues/810.
> QA/webconnectivity: check case of DNS based hijacking

- QA/webconnectivity.py
- experiment/webconnectivity/dnsanalysis.go
- experiment/webconnectivity/dnsanalysis_test.go
- experiment/webconnectivity/httpanalysis.go
- experiment/webconnectivity/httpanalysis_test.go
- experiment/webconnectivity/internal/internal.go
- experiment/webconnectivity/internal/internal_test.go
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
- experiment/webconnectivity/webconnectivity.go
We already know that probe-engine does better than MK when there is a control
failure and the website is using HTTPS and we can access it.
MK would flag such case as failed measurement, where instead probe-engine
would flag such case as success.
What we can instead test here is what happens if the same happens but we're
accessing a website using HTTP rather than HTTPS.
This QA test allowed us to discover the following issues:
1. MK always sets the body proportion to zero, even when performing such a
comparison is not actually possible, so do the same also in probe-engine even
though probably using `null` would be a more consistent result
2. MK sets the DNSConsistency field only when the control succeded and we
should do the same rather than flagging the DNS as consistent
This diff …
> QA/webconnectivity: control failure w/ HTTP website

- QA/webconnectivity.py
The behavior of probe-engine is better than the one of MK. We have
disabled this check for MK and we should open an issue.
The following diff shows the difference in the toplevel keys:
```diff
--- MK.jsonl	2020-08-13 13:12:05.741791884 +0200
+++ OPE.jsonl	2020-08-13 13:12:14.092840549 +0200
@@ -1,9 +1,9 @@
{
"input": "http://antani.xyz",
"test_keys": {
-    "accessible": true,
+    "accessible": null,
"agent": "redirect",
-    "blocking": false,
+    "blocking": null,
"body_length_match": null,
"body_proportion": 0,
"client_resolver": "91.80.36.88",
@@ -16,15 +16,16 @@
"body_length": -1,
"failure": "dns_lookup_error",
"headers": {},
-        "status_code": -1
+        "status_code": -1,
+        "title": ""
},
"tcp_connect": {}
},
"control_failure": null,
"dns_consistency": "consistent", …
```
> QA/webconnectivity.py: add test case for nonexistent domain

- QA/common.py
- QA/webconnectivity.py
- experiment/webconnectivity/webconnectivity.go
We open a listening port on localhost but we don't listen to such
port. We redirect HTTP to such port. So connect fails.
We also hijack the DNS such that the target host is localhost.
While there, fix printing the DNS consistency check result.
I have manually checked we match MK's behaviour.
> QA/webconnectivity: TCP/IP blocking w/ inconsistent DNS

- QA/webconnectivity.py
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
Make sure we do the same MK would do in this case.
Part of https://github.com/ooni/probe-engine/issues/810.
> QA/webconnectivity: connection refused in redirect chain

- QA/webconnectivity.py
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
This impacts on https://github.com/ooni/probe-engine/issues/579.
Part of https://github.com/ooni/probe-engine/issues/810.
> QA/webconnectivity: do like MK when domain is NXDOMAIN

- QA/webconnectivity.py
Objective is making sure we don't do different from MK as much
as possible as far as we can predict censorship cases.
> QA/webconnectivity: RST happens after redirect

- QA/webconnectivity.py
Strictly speaking we don't need a redirect chain to perform
this measurement but we have been hiding the initial request
from TCP/IP errors, so let's keep using that pattern.
> QA/webconnectivity: EOF in the redirect chain

- QA/webconnectivity.py
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
- netx/archival/archival.go
- netx/archival/archival_test.go
Again, likely doing the redirect chain is not necessary. But it makes
things more interesting, because we are testing stuff that happens after
the initial DNS, TCP, etc. checks performed by Web Connectivity.
> QA/webconnectivity: timeout error in redirect chain

- QA/minioonilike.py
- QA/webconnectivity.py
> QA/webconnectivity: check for successful HTTP{,S} measurement

- .github/workflows/qa.yml
- QA/webconnectivity.py
While there, make sure we run QA checks periodically.
Mostly using the same code used for periodic golang checks.
Useful to have so that, even if we're not developing, we know we
are actually running periodic checks for QA.
> QA/webconnectivity: http-diff w/ {,in}consistent DNS

- QA/webconnectivity.py
Related to https://github.com/ooni/probe-engine/issues/858
> QA/webconnectivity: several checks for TLS failures

- QA/webconnectivity.py
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
When working on this, notice that we were not correctly handling this
specific case, handle it and add also a test for that.
While there, notice that MK is not handling this case correctly and
file an issue for that: https://github.com/measurement-kit/measurement-kit/issues/1931
> QA/webconnectivity: censorship using NXDOMAIN

- QA/webconnectivity.py
It seems using neverssl.com isn't working well as a target for us
when running inside of github actions as documented in
https://github.com/ooni/probe-engine/issues/861.
For this reason, let us try with example.org as target instead.
> QA/webconnectivity: repair flaky test

- QA/webconnectivity.py
- experiment/webconnectivity/summary.go
- experiment/webconnectivity/summary_test.go
The status flags allow us to measure in a more precise way why and how
we flag a measurement as such. The flags are currently marked as an
experimental feature. I see them as a tool to:
1. make sure we can assert more precisely in tests why a specific
censorship condition led to a specific result
2. see quite clearly what are the places in which our understanding
of what went wrong is not very precise
After this last round of QA, I have covered most of the error conditions
specified in summary.go, and verified that the behavior that we are
implementing now is consistent with MK in such cases.
Therefore, with the merging of this diff, we will be reaching the point
where https://github.com/ooni/probe-engine/issues/852 is done.
> QA/webconnectivity: introduce status flags

- experiment/urlgetter/urlgetter.go
- libminiooni/libminiooni.go
Part of https://github.com/ooni/probe-engine/issues/655
> urlgetter: set default timeout when run from command line

- experiment/webconnectivity/control.go
- geolocate/README.md
- geolocate/avast.go
- geolocate/invalid_test.go
- geolocate/iplookup.go
- geolocate/iplookup_test.go
- geolocate/mmdblookup.go
- geolocate/mmdblookup_test.go
- geolocate/resolverlookup.go
- geolocate/resolverlookup_test.go
- geolocate/ubuntu.go
- netx/archival/archival.go
- session.go
Again, simplification preparing a blog post on probe-engine
as documented in https://github.com/ooni/probe-engine/issues/746.
> geoiplookup: simplify and rename geolocate

- cmd/miniooni/README.md
- cmd/miniooni/main.go
- libminiooni/README.md
- libminiooni/libminiooni.go
This cannot be a fast moving research client if we are strongly constrained
by backwards compatibility with previous CLI interfaces.
Also, I discovered that, sadly, we've already broken OONI Probe v2.x CLI
by giving another semantics to `-i` and `-O`.
Therefore, really be explicit in our goal of moving fast and do research and
hence give up on backwards compatibility for miniooni.
While there, yet, aim for some consistency and use `--probe-services` as
a command line flag rather than `--probe-services-url`, which is redundant.
Also, remove unused `--bouncer` and `--collector` options which were only
cluttering the output and making the code more complicated.
Do not remove the `--no-geoip` option because it seems we're going to have to
support this functionality again in the future, to …
> [API CHANGE] libminiooni: give up backwards compatibility and document

- go.mod
- go.sum
It seems github.com/pborman/getopt v2.0.0 disappeared?! This breaks `go get -v github.com/ooni/probe-engine`, which is not good at all. Let's see whether bumping getopt to v2.1.0 means that we can run the above command.
Part of https://github.com/ooni/probe-engine/issues/746
> go.mod go.sum: upgrade to pborman/getopt v2.1.0

- netx/netx.go
Part of https://github.com/ooni/probe-engine/issues/359, which is
now closed. Seems fine to provide explicit links in the doc.
> doc(netx/netx.go): explicitly link to issue describing design

- experiment.go
- oonimkall/task_test.go
- oonimkall/tasks/chanlogger.go
- oonimkall/tasks/event.go
- oonimkall/tasks/eventemitter.go
- oonimkall/tasks/eventemitter_test.go
- oonimkall/tasks/runner.go
- oonimkall/tasks/runner_internal_test.go
- oonimkall/tasks/runner_test.go
External testing is better because it explicits what is the API.
I would also like to have very good inter package coverage. In this
case, sadly, it means duplicating some tests.
I think there is more yak shaving to rationalize and speed up
tests within oonimkall a bit, but not immediately.
This finishes the yak shaving before fully tackling
https://github.com/ooni/probe-engine/issues/893.
> oonimkall: use external testing and better coverage

- probeservices/collector.go
- probeservices/collector_test.go
The criteria is: if the report template matches, there is no point
in opening a new report. Otherwise, yes, they are different reports.
Needed by https://github.com/ooni/probe-engine/issues/893
> probeservices: teach report to recognise its measurements

- probeservices/collector.go
- probeservices/collector_test.go
The submitter will take in input measurements and do the right thing
with respect to using the current report or open a new one.
With this functionality implemented, we have now all the building
blocks required by https://github.com/ooni/probe-engine/issues/893.
> probeservices: introduce the concept of the submitter

- experiment.go
- probeservices/collector.go
- probeservices/collector_test.go
The field is deprecated but not using it is going to change the
resubmitter behavior wrt MK's submitter.
So, let's be pragmatic and add this field again.
See https://github.com/ooni/probe-engine/issues/893#issuecomment-686973455
> probeservices: add test_start_time to open-report request

- version.go
With the version bump, we're ready to merge into mobile-staging so that
we can start testing the new code with Android and iOS.
Part of https://github.com/ooni/probe-engine/issues/893
> version.go: bump to 0.17.0-beta

- oonimkall/README.md
- oonimkall/session.go
- oonimkall/task.go
- oonimkall/uuid.go
Part of finishing https://github.com/ooni/probe-engine/issues/893 and
of ensuring the Session API we're exposing is compliant with the compact
design at https://github.com/ooni/probe-engine/issues/893#issuecomment-689031449.
> oonimkall: review and update the documentation

- DESIGN.md
We've added new APIs in https://github.com/ooni/probe-engine/issues/893
but we didn't feel the need of updating DESIGN.md, rather it was more
productive to use an issue as a designing tool.
This is all fine and we should do whatever works(tm) but we should also
make sure we don't provide false expectations with DESIGN.md.
A cheap way to do that is to clearly mark this design document scope
to be that of describing how to replace Measurement Kit.
> DESIGN.md: restrict the scope of the design document

- libminiooni/libminiooni.go
- libminiooni/libminiooni_unit_test.go
It didn't occur to me initially, but the fact that vim adds a newline at
the end of the file adds an extra blank input to be tested.
We actually don't want to emit an error for such an input and the fix
is just to avoid adding blank inputs to the inputs list.
Since the fix is so easy, while there allow any other blank line in
the middle of the file, since it costs us nothing.
Part of https://github.com/ooni/probe-engine/issues/926
> libminiooni: allow newline at EOF with -f/--file

- internal/mlablocatev2/mlablocatev2.go
See https://github.com/ooni/probe-engine/issues/930
> internal/mlablocatev2: use v2/nearest API

- experiment/fbmessenger/fbmessenger_test.go
- experiment/hhfm/hhfm_test.go
- experiment/hirl/hirl_test.go
- experiment/webconnectivity/webconnectivity_test.go
- internal/mockable/mockable.go
- oonimkall/session_test.go
- probeservices/probeservices_test.go
- probeservices/urls_test.go
- session_test.go
There are two reasons for this change:
1. we wanna make sure ams-pg.ooni.org passes all tests
2. mia-ps-test.ooni.io is currently broken
See https://github.com/ooni/backend/issues/446
> all: use ams-pg.ooni.org as testing probe service

- .github/workflows/generate.yml
- .github/workflows/jafar.yml
- .github/workflows/libooniffi.yml
- .github/workflows/miniooni.yml
- .github/workflows/qa.yml
- .github/workflows/using.yml
Push is not triggered for external pull requests and, at the same time, it
makes sense we run more thorough checks when we have a PR.
Noticed when reviewing https://github.com/ooni/probe-engine/pull/944.
> github/workflows: run more checks on pull request

- build-cli.sh
- readme_compiletimecheck.go
> workaround to build probe-engine with go1.15

- .github/workflows/go115.yml
- .github/workflows/miniooni.yml
- build-cli.sh
- readme_compiletimecheck.go
This diff contains a bunch of small cosmetic tweaks for https://github.com/ooni/probe-engine/issues/866 as well as a smoke test to make sure we're not going to break future builds of people using Go 1.15.
> go1.15 workaround: add integration test and explanatory output

- legacy/netx/resolver_test.go
- netx/resolver/integration_test.go
- oonimkall/session.go
- oonimkall/session_internal_test.go
- oonimkall/session_test.go
- oonimkall/task.go
- session.go
When helping @lorenzoPrimi with https://github.com/ooni/probe-android/pull/360
I had the impression there was too much complexity.
Then we said we could improve the situation by changing the class names
as written in https://github.com/ooni/probe-engine/issues/951#issue-708184925.
But then there was still too much complexity. I could not easily picture in
my mind why each class was needed. This was actually a strong signal that we
needed to refactor the code more than just renaming clases.
So, here's the new approach (for which I'll write soon a mini design document
that will be referenced inside the code - or maybe this is the document!):
1. Session uses runtime.SetFinalizer therefore we don't need to be concerned
about wrapping it and using AutoCloseable in Java. It is not normal for Go …
> oonimkall/session.go: significantly simplify the implementation

- internal/psiphonx/psiphonx.go
- internal/sessiontunnel/sessiontunnel.go
- internal/torx/torx.go
- model/experiment.go
ExperimentSession is a large interface in the model package that is
too large and too widely used to be easily modifiable.
I noticed this issue when I started investigating the issue at
https://github.com/ooni/explorer/issues/495.
Before we embark into more substantial changes, let us clear the
table a little bit by reducing the scope of ExperimentSession.
> refactor(model/experiment.go): less code depends on ExperimentSession (1/n)

- probeservices/benchselect.go
- probeservices/probeservices.go
This continues the work initiated in https://github.com/ooni/probe-engine/pull/960 and the rationale is also of course the same. This work is indeed yak shaving while looking into https://github.com/ooni/explorer/issues/495.
> refactor(model/experiment.go): less code depends on ExperimentSession (2/n)

- experiment/dash/dash_test.go
- experiment/example/example_test.go
- experiment/hhfm/hhfm_test.go
- experiment/hirl/hirl_test.go
- experiment/ndt7/ndt7_test.go
- experiment/psiphon/psiphon_test.go
- experiment/sniblocking/sniblocking_test.go
- experiment/stunreachability/stunreachability_test.go
- experiment/telegram/telegram_test.go
- experiment/tor/tor_test.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/multi_test.go
- experiment/urlgetter/urlgetter_test.go
- experiment/webconnectivity/control_test.go
- experiment/whatsapp/whatsapp_test.go
- internal/mockable/mockable.go
- internal/psiphonx/psiphonx_test.go
- internal/sessiontunnel/sessiontunnel_test.go
- internal/torx/torx_test.go
- model/experiment.go
- probeservices/probeservices_test.go
This concludes our initial yak shaving journey. Now the view of a Session that
experiments have is significantly simpler than before.
I see this diff as a preliminary change aimed at facilitating investigating
https://github.com/ooni/explorer/issues/495 in the probe context.
> refactor(model/experiment.go): less code depends on ExperimentSession (3/3)

- experiment/webconnectivity/webconnectivity.go
- experiment/webconnectivity/webconnectivity_test.go
- internal/mockable/mockable.go
- model/experiment.go
- session.go
- session_test.go
Since this experiment has been rewritten in Go, we can safely omit the
IP address of the client resolver. The new implementation, in fact,
performs a geolookup of such an IP address.
Not strictly and directly related with the issue I am working on
(https://github.com/ooni/explorer/issues/495). Yet, working on such
an issue and reading the code is a useful mindset to reason about
simplifications around what we submit to our backends.
> webconnectivity: we can now safely omit client resolver IP

- model/model_test.go
- model/privacysettings.go
With https://github.com/ooni/probe-engine/pull/966 and this change
together we have a more in depth mechanism for enforcing that we're
doing the right thing in terms of honouring sharing settings.
Yet, my instinct is that we should push for removing this vestigial
options that increase complexity and reduce the quality of data we
receive, in the mid term. Shall discuss this with the rest of the team.
> fix(model): make sure we honour sharing settings

- build-ios.bash
Part of https://github.com/ooni/probe-engine/issues/668
> build-ios.bash: remove workaround required by ObjectiveC++

- netx/netx.go
Fix #657
`$ ./miniooni -i dot://1.0.0.1 dnscheck` :
> dns: set dot to ALPN

- .github/workflows/golang.yml
- experiment/example/example.go
- experiment/example/example_test.go
- experiment/fbmessenger/fbmessenger_test.go
- experiment/hhfm/hhfm_test.go
- experiment/hirl/hirl_test.go
- experiment/ndt7/ndt7.go
- experiment/ndt7/ndt7_test.go
- experiment/stunreachability/stunreachability_test.go
- experiment/webconnectivity/connects_test.go
- experiment/webconnectivity/dnslookup_test.go
- experiment/webconnectivity/httpget_test.go
- experiment/webconnectivity/webconnectivity_test.go
For pull requests (and possibly also for master) we generally want to run
short tests because this allows for faster feedback cycles.
To this end, this PR strives to flag as "long" tests that take too much time
and also cuts the time consumed by tests that can be easily optimised.
Part of https://github.com/ooni/probe-engine/issues/1005.
> fix: only run short tests

- .github/ISSUE_TEMPLATE/routine-sprint-releases.md
- .github/workflows/alltests.yml
- .github/workflows/shorttests.yml
- README.md
Rename golang.yml as shorttests.yml and update README.md to point
to this new workflow for showing users a badge.
Write a new alltests.yml workflow that runs daily and includes all
tests, including the ones that are currently failing now.
See https://github.com/ooni/probe-engine/issues/1005.
> fature: run comprehensive tests every day

- .github/workflows/alltests.yml
- internal/sessionresolver/sessionresolver.go
- internal/sessionresolver/sessionresolver_test.go
- session.go
See https://github.com/ooni/probe-engine/issues/1005
> fix(sessionresolver): use dns.quad9.net

- allexperiments.go
- experiment/httphostheader/httphostheader.go
- experiment/httphostheader/httphostheader_test.go
- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
It seems that example.org is a more reliable helper.
Related spec change: https://github.com/ooni/spec/commit/1d3000437f19f4b3214116eae288032996dd53f8
Work done in the context of: https://github.com/ooni/probe-engine/issues/622
> fix: use example.org rather than example.com

- cmd/jafar/iptables/iptables_integration_test.go
- cmd/jafar/iptables/iptables_linux.go
- cmd/jafar/shellx/shellx.go
- cmd/jafar/shellx/shellx_test.go
- model/logger.go
- model/model_test.go
- session_integration_test.go
This is especially helpful when trying to understand what kind of
error or errors has caused test runs to fail.
This specific issue with out test harness has been bugging me when
working on https://github.com/ooni/probe-engine/issues/974.
In addition to making tests more silent, this PR also fixes the way in
which we waive policies for iptables so it's consistent across runs
also in case, for some reason, one of the tests fails.
> fix: more quiet tests, more predictable iptables tests

- experiment/dash/dash.go
- experiment/dash/dash_test.go
Here the idea is to make the dash experiment such that we can
easily ask it about summary test keys and a log summary from
probe-cli. This allows to get rid of some code that should not
actually be part of probe-cli. In turn, the objective here is
to further the integration between the two code bases to ensure
we can tell probe-cli to run nettests using specific inputs as
documented by https://github.com/ooni/probe/issues/1283.
I'm proceeding piecemeal, adding functions to each experiment
and then ensuring all experiments have the same functions. Thus
this is just the first ~small diff of many.
> feat(dash): introduce APIs used by probe-cli

- experiment/dnscheck/dnscheck.go
- experiment/dnscheck/dnscheck_test.go
- experiment/example/example.go
- experiment/example/example_test.go
- experiment/httphostheader/httphostheader.go
- experiment/httphostheader/httphostheader_test.go
- experiment/riseupvpn/riseupvpn.go
- experiment/riseupvpn/riseupvpn_test.go
- experiment/sniblocking/sniblocking.go
- experiment/sniblocking/sniblocking_test.go
- experiment/stunreachability/stunreachability.go
- experiment/stunreachability/stunreachability_test.go
- experiment/tlstool/tlstool.go
- experiment/tlstool/tlstool_test.go
- experiment/urlgetter/urlgetter.go
- experiment/urlgetter/urlgetter_test.go
Same as 46e42dc2a7ca70aebd941f9081fb58a3e98b0d7c but this time
we're dealing with experiments that currently we're not running
from probe-cli, so it's easy to support them.
Part of https://github.com/ooni/probe/issues/1283.
> feat: continue introducing API used by probe-cli

- experiment/fbmessenger/fbmessenger.go
- experiment/fbmessenger/fbmessenger_test.go
Same as 46e42dc2a7ca70aebd941f9081fb58a3e98b0d7c but this time
we're dealing with fbmessenger.
Part of https://github.com/ooni/probe/issues/1283.
> feat(fbmessenger): continue introducing API used by probe-cli

- experiment/fbmessenger/fbmessenger.go
- experiment/fbmessenger/fbmessenger_test.go
- experiment/hhfm/hhfm.go
- experiment/hhfm/hhfm_test.go
While there, remember to also bump fbmessenger version number.
> feat(hhfm): continue introducing api required by probe-cli

- oonimkall/sessioncontext_test.go
This diff fixes the context timeout not working as intended bug
described in https://github.com/ooni/probe-engine/issues/994.
Before canceling the context we need to increase the counter so that
we're sure that canceling the context happens _after_ we increased
the counter. Otherwise, it may actually happen before depending on the
choices made by the Go scheduler.
Closes https://github.com/ooni/probe-engine/issues/994. If I am
wrong we will reopen, but I think this is at least a good explanation.
> fix context timeout not working as intended bug

- experiment.go
- experiment/psiphon/psiphon_test.go
- experiment/webconnectivity/connects.go
- experiment_integration_test.go
- model/experiment.go
- model/experiment_test.go
- oonimkall/tasks/runner.go
This callback is unused since we removed MK, as very cleary specified
in the sources of probe-cli. For this reason, I thought it was time for
us to get rid of this deprecated, unused piece of code.
See https://github.com/ooni/probe/issues/1283
> cleanup: remove unused OnDataUsage

- experiment.go
This wrapper is now unused and it's only annoying me while I am
working towards https://github.com/ooni/probe/issues/1283.
> cleanup(experiment.go): remove unused callbacks wrapper

- experiment.go
- libminiooni/libminiooni.go
- submitter.go
- submitter_test.go
This is a small abstraction that allows us to simplify code that is
submitting measurements by eliminating conditionals.
Work part of https://github.com/ooni/probe/issues/1283.
> feat(engine): create Submitter abstraction

- libminiooni/libminiooni.go
- saver.go
- saver_test.go
- submitter_test.go
Same design of Submitter, except we use it for saving measurements
on the file system. While there, tweak submitter tests.
Reference issue: https://github.com/ooni/probe/issues/1283.
> feat(engine): introduce the Saver abstraction

- inputloader.go
- inputloader_integration_test.go
- inputloader_test.go
- libminiooni/libminiooni.go
- saver.go
- saver_test.go
- submitter.go
- submitter_test.go
We need InputLoader to be an interface because:
1. its implementation is actually quite appropriate for an interface
since we select different code paths depending on the policy
2. an interface is easier to wrap for probe-cli
While there, don't name config structs like NewFooConfig because the
NewSomething pattern in Go implies a factory, so better to avoid being
confusing with naming.
Notwithstanding point 1. above, I'm not doing a full refactoring to
an interfaces based implementation for InputLoader because the existing
code is already good and we don't need this change now.
This diff is part of https://github.com/ooni/probe/issues/1283.
> fix(engine): InputLoader's now an interface

- inputprocessor.go
- inputprocessor_test.go
- libminiooni/libminiooni.go
- saver.go
- saver_test.go
- submitter.go
- submitter_test.go
The InputProcessor should capture the behaviour of any code that
is processing input to run an experiment.
Users should be able to customise this behaviour by wrapping specific
interfaces with other interfaces implementing state monads.
This work is part of https://github.com/ooni/probe/issues/1283
> feat(engine): introduce InputProcessor abstraction

- experiment/urlgetter/urlgetter.go
- experiment/urlgetter/urlgetter_test.go
- probeservices/urls_test.go
Related to https://github.com/ooni/probe-engine/issues/1055.
> fix(urlgetter): say we're using the tcpconnect data format

- libminiooni/libminiooni.go
The removal of --no-geoip stems from the fact that now we require
measurements to be geolocated (see https://github.com/ooni/probe-engine/issues/974).
The removal of --no-bouncer is because that option was added some
time ago for MK compatibility, but we've later decided that we don't
want to provide any compatibility guarantee, so we can happily get
rid of this option, which is only adding extra complexity.
> libminiooni: remove --no-bouncer and --no-geoip

- oonimkall/task_integration_test.go
- oonimkall/tasks/runner.go
- oonimkall/tasks/runner_integration_test.go
- oonimkall/tasks/runner_internal_test.go
- oonimkall/tasks/settings.go
This diff removes all the legacy options. We now require a `version`
field to be present in the top-level settings and equal to 1.
I started this diff as a minimal attempt to cleanup oonimkall after
https://github.com/ooni/probe-engine/issues/974, but then realised the
time was ripe for a more fundamental cleanup.
Cc: @lorenzoPrimi.
> [MOBILE API CHANGE] cleanup(oonimkall): remove legacy options

- netx/netx.go
We can remove redundant structure tags from there.
Part of https://github.com/ooni/probe-engine/issues/1057.
> fix(netx.go): address linter warning

- experiment.go
- inputprocessor.go
- inputprocessor_test.go
Noticed while working on https://github.com/ooni/probe-engine/issues/1057.
> fix(inputprocessor): merge annotations rather overwriting them

- libminiooni/libminiooni.go
- saver.go
- saver_test.go
- submitter.go
- submitter_test.go
While working on https://github.com/ooni/probe-engine/issues/1057, I noticed
that since recent changes in probe-engine that introduced Saver and Submitter,
we've got logging wrong. We should actually be logging only when we're are
submitting and/or saving, and we shan't be logging otherwise.
While there, make sure we continue to print the reportID, which is a very
useful piece of information to see emitted by miniooni.
> fix(saver, submitter): make sure we only log when needed

- .github/workflows/codeql-analysis.yml
- internal/mlablocatev2/mlablocatev2.go
See https://github.com/ooni/probe-engine/security/code-scanning/2
> fix(mlablocatev2.go): correctly quote dots in regexp

- experiment/whatsapp/whatsapp.go
See https://github.com/ooni/probe-engine/security/code-scanning/1
> fix(whatsapp): escape all dots in regexp

- libminiooni/libminiooni.go
For ooniprobe we use --input-file to indicate the file to read input
from. Let us use the same CLI flag for consistency.
Done while working on https://github.com/ooni/probe-engine/issues/1115.
> [CLI CHANGE] feat(libminiooni): use --input-file like ooniprobe

- experiment/dnscheck/dnscheck.go
- experiment/urlgetter/urlgetter.go
While there, tweak the documentation for HTTP3Enabled for both
urlgetter and dnscheck. While there, tag dnsheck options so that
they use snake case when they are serialised to JSON.
The latter change will become useful in the next pull request.
Part of https://github.com/ooni/probe-engine/issues/1115.
> feat(dnscheck): allow users to force http3

- allexperiments.go
- experiment/dnscheck/dnscheck.go
- experiment/dnscheck/dnscheck_test.go
- experiment/run/dnscheck.go
- experiment/run/run.go
- experiment/run/run_test.go
- experiment/run/table.go
This experiment takes in input one or more JSON documents. Each
JSON document describes an experiment that should be run.
The document also allows you to specify all the settings for the
experiment. We currently only support dnscheck.
This is an example of input file:
```JSON
{"name": "dnscheck", "input": "https://dns.google/dns-query", "dns_check":{"http3_enabled": true, "domain": "x.org"}}
{"name": "dnscheck", "input": "dot://dns.google", "dns_check":{"domain": "x.org"}}
```
This runs dnscheck twice. The first time using Google's DoH over
http3, for x.org. The second time using Google's DoT.
Part of https://github.com/ooni/probe-engine/issues/1115.
> feat: introduce the experimental run experiment

- allexperiments.go
- experiment/run/run.go
- experiment_integration_test.go
- experimentbuilder.go
- inputloader.go
- inputloader_integration_test.go
- oonimkall/tasks/runner.go
We used to have InputRequired category, which meant that you were
providing input and, if there was not input, we would then use the
test-lists API to fetch input URLs.
This policy was used, however, improperly in some cases. As noted
in https://github.com/ooni/probe-engine/issues/1123, dnscheck would
for example use the test lists if no input was provided. Sadly,
though, such input does not make any sense when provided to dnscheck,
which leads to miniooni running very useless tests.
So, here's an improvement:
1. we rename InputRequired to InputOrQueryTestLists, which BTW
captures in an even better way the original intent
2. we introduce InputStrictlyRequired, where, if there is no
input, we just fail, and we apply it to dnscheck, run, and all
the cases in which it makes sense to use this …
> feat(experiment): split InputRequired policy

- netx/archival/archival.go
- netx/archival/archival_test.go
Discovered while working on https://github.com/ooni/probe-engine/issues/1115.
> fix(archival): don't include UDP conns in tcp_connect

- experiment/dnscheck/dnscheck.go
- experiment/dnscheck/dnscheck_test.go
This allows to set this option more easily using -O.
Part of https://github.com/ooni/probe-engine/issues/1115.
> fix(dnscheck): defaultaddrs is now a string

- experiment/riseupvpn/riseupvpn_test.go
See https://github.com/ooni/probe-engine/issues/1137.
> fix(riseupvpn): we can re-enable a disabled test

- experiment.go
- experiment_integration_test.go
- model/measurement.go
- oonimkall/session.go
- oonimkall/tasks/runner.go
- probeservices/collector.go
- probeservices/collector_test.go
- submitter.go
The close operation is now a relic of the past that we support
only for the sake of legacy clients.
So, we can remove it and simplify the code a little bit.
While there, make sure we use an interface for the opened report
rather than a struct, so we can improve testing in the future.
Also, the OOID is currently not returned by any collector, hence
it does not make any sense to have code handling it.
Work done as cleanup after https://github.com/ooni/probe-engine/issues/948.
> cleanup(report): remove report.close operation

- experiment/run/dnscheck.go
Otherwise measurements are submitted as part of the run
experiment, which is very unhelpful.
See https://github.com/ooni/probe-engine/issues/1115.
> fix(run): set dnscheck name and version

- experiment/dnscheck/dnscheck.go
- experiment/dnscheck/dnscheck_test.go
- experiment/urlgetter/getter.go
- experiment/urlgetter/getter_test.go
- experiment/urlgetter/urlgetter.go
1. avoid setting a unique timeout for the whole measurement
2. set a 20 seconds timeout for the bootstrap
3. use up to 10 concurrent goroutines for the lookups
4. set a 45 seconds timeout for each individual lookup
5. urlgetter/getter.go: introduce a timeout (for now do not
expose it to command line since that is more work)
6. urlgetter/urlgetter.go: use the new timeout in getter.go
7. urlgetter/getter.go: add tests for the timeout case
See https://github.com/ooni/probe-engine/issues/1159
> fix(dnscheck): avoid false positive due to timeout

- experiment/riseupvpn/riseupvpn.go
- experiment/urlgetter/multi.go
Currently the `Multi.Collect()` method calculates the progress of a task based on the length of the `MultiInput` array. If an experiment performs multiple times `Multi.Collect()` the progress repeats increasing from 0% to 100%. This is especially an issue for a GUI client such as OONI Android, as it shows confusing estimations about the expected remaining runtime of a test. The shown expected time decreases multiple times to 0s and starts over again with a higher expected remaining time.
This PR introduces a method `Multi.CollectOverall()` that calculates the progress over multiple collection tasks. It is used in the RiseupVPN experiment. 
I would be interested to know if you see other/better options to archive the same goal.
> fix(urlgetter): progress over multiple collection tasks

- experiment/webconnectivity/webconnectivity.go
Part of https://github.com/ooni/probe-engine/issues/1170
> fix(webconnectivity.go): print which test helper we use

- .github/workflows/miniooni.yml
- CLI/linux/386/.gitignore
- CLI/windows/386/.gitignore
- build-cli.sh
Written while working on https://github.com/ooni/probe/issues/1315
> build-cli.sh: support windows/386 and linux/386

- experiment/ndt7/download.go
The reader is already fully read, so falling through does not have
side effects. But doing a continue is cleaner.
While there, make sure we account for TextMessages size.
> fix(ndt7): continue after TextMessage

- netx/archival/archival.go
We wrongfully didn't store the TLS information (such as peer certificates, cipher suite) for QUIC. This is fixed by this PR.
> (fix) quic saver: store TLS handshake info

- netx/quicdialer/saver.go
> (fix) quic saver: return nil instead of err
