cmd/miniooni/main.go, session/session.go
closes #32
Files changed:
- session/session.go
- cmd/miniooni/main.go
Renamed functions:
- SetAvailableHTTPSCollector => AddAvailableHTTPSCollector
- SetAvailableHTTPSBouncer => AddAvailableHTTPSBouncer
=> session: rename SetAvailableHTTPS* to AddAvailableHTTPS*

cmd/miniooni/main.go
=> Make minooni logging simpler and more actionable

cmd/miniooni/main.go, experiment/example/example.go, experiment/example/example_test.go
=> Add example experiment

collector/collector.go, collector/collector_test.go, experiment/experiment.go
Spotted by @FedericoCeratto (thanks!)
"This could have been avoided with end-to-end testing" 🤦
=> fix(collector): specify format and data-format-version

experiment/dash/dash_cgo.go, experiment/dash/dash_cgo_test.go, experiment/dash/dash_otherwise.go, experiment/dash/dash_otherwise_test.go
close #51
(I'm not sure whether the codes is correct or not.)
=> dash: rewrite using neubot/dash

experiment/experiment.go
Hunk approved by @hellais in #96. Going to hotfix this.
=> experiment.go: fix measurement runtime

collector/collector_test.go
=> collector: don't use hkgcollectora

orchestra/testlists/testlists.go
=> orchestra: use canonical path

collector/collector.go, experiment/mkevent/mkevent.go
Issue reported by @FedericoCeratto
=> collector: unconditionally write the ReportID

resources/assets.go
=> Use ooni/probe-engine@20191129161951

experiment/dash/dash_otherwise.go, experiment/dash/dash_otherwise_test.go, experiment_test.go
=> dash: refactor and write more tests

experiment/psiphon/psiphon.go
After looking into the data model of the previous version, I have
determined it's not the case to seek for 100% backwards compat.
I have added all the ooni/probe-legacy psiphon experiment keys that
are still easy and meaningful. Here's what has changed:
1. the name of the temporary file is not relevant anymore as are
not relevant the exit code and the stdout/stderr
2. psiphon_installed does not make any sense
3. success could still be here, but TBH I belive it's much more
informative to have a nullable failure string
4. body is not here because we already have it in the HTTP requests
5. default_configuration is a key for which I cannot totally
understand what could be the use in this new scenario, but we
may probably want to discuss that?
6. I've chosen to use the HTTP data format of Web …
=> psiphon: refine the output data model

experiment/httpheader/accept.go, experiment/httpheader/acceptlanguage.go, experiment/httpheader/useragent.go, experiment/psiphon/psiphon.go, experiment/telegram/telegram_otherwise.go
=> http: also send Accept{,-Language}

experiment/oodatamodel/oodatamodel.go, experiment/oodatamodel/oodatamodel_test.go, experiment/psiphon/psiphon.go, experiment/telegram/telegram_otherwise_test.go
Unsure whether this could happen, but robustness is usually good.
Closes #110
=> oodatamodel: handle binary header values

internal/orchestra/metadata/metadata.go, internal/orchestra/orchestra.go, internal/orchestra/register/register.go, internal/orchestra/register/register_test.go
=> orchestra: implement registering a probe

internal/orchestra/login/login.go, internal/orchestra/login/login_test.go
=> orchestra: implement logging in a probe

internal/orchestra/orchestra.go, internal/orchestra/orchestra_test.go, internal/orchestra/testorchestra/testorchestra.go
=> orchestra: implement client with authenticated APIs

experiment/dash/dash_otherwise.go
=> dash: make sure failure is `*string`

internal/platform/platform.go, internal/platform/platform_cgo.go, internal/platform/platform_otherwise.go, internal/platform/platform_test.go, session.go, session_test.go
=> Implement and use MK-like platform detection

.gitignore, httpx/fetch/fetch.go, internal/orchestra/orchestra.go, internal/orchestra/orchestra_test.go, internal/orchestra/testlists/psiphon/psiphon.go, internal/orchestra/testlists/psiphon/psiphon_test.go, internal/orchestra/update/update.go, testdata/.gitignore
=> orchestra: fetch psiphon config via auth request

experiment/oodatamodel/oodatamodel.go, experiment/oodatamodel/oodatamodel_test.go
=> http: save headers as a list

internal/oonidatamodel/oonidatamodel.go, internal/oonidatamodel/oonidatamodel_test.go
Before this diff, we could not unmarshal when the body was binary
as I discovered while working on #2. This diff fixes it.
=> oonidatamodel: ensure maybe-binary values can round trip

experiment/telegram/telegram.go
Turns out that my understanding of data races was imprecise.
While there, apply some cosmetic changes.
Discovered while working on #2 and #90, which use a similar design.
=> telegram.go: eliminate a data race

internal/oonitemplates/oonitemplates.go
I'd like to include the events to the output of #90.
=> oonitemplates.go: start exporting network events

httpx/httplog/httplog.go, internal/netxlogger/netxlogger.go, internal/tlsx/tlsx.go, internal/tlsx/tlsx_test.go
=> tlsx: factor common code for pretty printing

experiment/tor/tor.go, experiment/tor/tor_test.go
Closes https://github.com/ooni/probe-engine/issues/292
=> tor: introduce and fill toplevel keys

experiment/tor/tor.go, model/model.go
See https://github.com/ooni/sysadmin/commit/bf082ff0953d72bdf67773b2527716e50646908e
Part of https://github.com/ooni/probe/issues/973
=> tor: add support for or_port_dirauth

experiment.go, experiment/sniblocking/sniblocking.go, experiment/sniblocking/sniblocking_test.go, experiment_test.go
=> Implement sni_blocking experiment

experiment/tor/tor.go, experiment/tor/tor_test.go
Closes https://github.com/ooni/probe-engine/issues/304
Implements https://github.com/ooni/spec/commit/60215153936a9901a5b5b72f031f8db41136536d
=> experiment/tor: implement summary

resources/assets.go
=> assets.go: fetch URLs using https

cmd/miniooni/main.go
See https://github.com/ooni/probe-engine/issues/316
=> miniooni: submit and save also if measurement returns error

measurementkit/task_cgo.go
=> task_cgo.go: allow compiling on ordinary Linux systems

geoiplookup/mmdblookup/mmdblookup.go, internal/resources/assets.go
Part of https://github.com/ooni/probe-engine/issues/334
=> internal/resources: update assets to 20200225143707

oonimkall/chanlogger.go, oonimkall/event.go, oonimkall/eventemitter.go, oonimkall/eventemitter_test.go, oonimkall/runner.go, oonimkall/runner_test.go
Closes https://github.com/ooni/probe-engine/issues/348
=> oonimkall: never omit mandatory event fields

testlists.go
Makes the documentation more beautiful.
Part of https://github.com/ooni/probe-engine/issues/302.
=> testlists.go: use naming consistent with other files

experiment.go, experiment/sniblocking/sniblocking.go, experiment/sniblocking/sniblocking_test.go
Part of https://github.com/ooni/probe-engine/issues/388
=> sniblocking: use example.com as test helper

README.md
Part of https://github.com/ooni/probe-engine/issues/384.
While there, document the mobile API.
=> README.md: document how to build miniooni

oonimkall/runner.go
Closes https://github.com/ooni/probe-engine/issues/350
=> oonimkall now accurately counts bytes

.github/workflows/android.yml, MOBILE/template.pom, publish-android.bash
Includes instructions regarding how to delete old packages.
Closes https://github.com/ooni/probe-engine/issues/376.
=> Automatically publish packages using bintray

netx/dialer/dialer.go, netx/dialer/dialer_test.go, netx/dialer/dialerbase/dialerbase.go, netx/dialer/dialerbase/dialerbase_test.go, netx/dialer/dnsdialer/dnsdialer.go, netx/dialer/dnsdialer/dnsdialer_test.go, netx/dialer/tlsdialer/tlsdialer.go, netx/dialer/tlsdialer/tlsdialer_test.go
=> netx/dialer: start renaming items before merging packages

netx/dialer/connx.go, netx/dialer/connx_test.go, netx/dialer/dialer.go, netx/dialer/dialerbase.go, netx/dialer/dialerbase_test.go, netx/dialer/dnsdialer.go, netx/dialer/dnsdialer_test.go, netx/dialer/tlsdialer.go, netx/dialer/tlsdialer_test.go
This is part of https://github.com/ooni/probe-engine/issues/125
=> refactoring: netx/dialer: merge all packages

netx/dialer/dialerbase.go, netx/dialer/dialerbase_test.go, netx/dialer/dnsdialer.go, netx/dialer/tlsdialer_test.go
This is also part of https://github.com/ooni/probe-engine/issues/125
It seems there's some yak shaving involved, but I'm determined to
get to the bottom of it b/c this simplifies the job a lot.
=> Further simplify the interface between the dialers

netx/dialer/tls.go, netx/dialer/tls_test.go
=> netx/dialer: composable TLS handshaker implementation

netx/dialer.go, netx/dialer/dns.go, netx/dialer/dns_test.go
=> netx/dialer: move configuration at the netx level

netx/dialer.go, netx/dialer/base.go, netx/dialer/base_test.go
=> netx/dialer: separate err-wrapping and emitter conn

netx/dialer.go, netx/dialer/dns.go
For conveniency and similarly to NewTLSDialer.
See https://github.com/ooni/probe-engine/issues/125
=> netx/dialer: add factory to create DNSDialer

netx/dialer/bytecounter.go, netx/dialer/bytecounter_test.go, netx/dialer/dns.go, netx/dialer/tls.go
=> netx/dialer: add byte counting dialer

netx/resolver/ooni.go, netx/resolver/ooni_test.go, netx/resolver/parent_test.go, netx/resolver/resolver.go, netx/resolver/system.go, netx/resolver/system_test.go
=> refactor(netx/resolver): more consistent System resolver design

netx/resolver/dnsoverhttps.go, netx/resolver/dnsoverhttps_test.go, netx/resolver/dnsoverudp.go, netx/resolver/dnsoverudp_test.go, netx/resolver/fake_test.go
=> netx: refactor doh and dns-over-udp w/ unit tests

netx/resolver/decoder.go, netx/resolver/decoder_test.go, netx/resolver/encoder.go, netx/resolver/encoder_test.go, netx/resolver/ooni.go, netx/resolver/ooni_test.go
=> netx/resolver: encoder and decoder w/ unit testing

netx/resolver/emitter.go, netx/resolver/emitter_test.go, netx/resolver/system.go, netx/resolver/system_test.go
=> netx/resolver: standalone emitter resolver w/ unit tests

netx/dialer/dns.go, netx/dialer/dns_test.go
=> netx/dialer: write unit tests for dns.go

netx/dialer/eof_test.go, netx/dialer/integration_test.go, netx/dialer/tls.go, netx/dialer/tls_test.go
=> netx/dialer: write unit tests for TLS code

netx/dialer/bytecounter_test.go, netx/handlers/handlers_test.go
=> netx: make sure all pkgs have 100% coverage

oonimkall/runner.go, oonimkall/task_test.go
Part of the work to finally call https://github.com/ooni/probe-engine/issues/125 done
=> oonimkall: use bytes measured by the experiment

model/model.go
Finalizing https://github.com/ooni/probe-engine/issues/125
=> ExperimentCallbacks: mark OnDataUsage as deprecated

go.mod, go.sum, internal/resources/assets.go
Closes https://github.com/ooni/probe-engine/issues/396
=> Release v0.9.0

oonimkall/runner_test.go, oonimkall/task_test.go
Spotted while working on something else.
=> fix(oonimkall): don't write testdata outside of srcroot

oonimkall/runner.go
Closes https://github.com/ooni/probe-engine/issues/453
=> oonimkall/runner.go: more INFO messages

experiment/dash/client.go, experiment/dash/client_test.go, experiment/dash/dash.go, experiment/dash/dash_test.go
=> dash: use our internal mlabns client

experiment/dash/client.go, experiment/dash/client_test.go, experiment/dash/dash.go
=> dash: print server name after mlabns call

experiment/dash/dash.go, libooniffi/ooniffi.go
=> dash: report speed in kbit/s

experiment/dash/client.go, experiment/dash/client_test.go, experiment/dash/dash.go
=> dash: save and populate the connect latency

experiment/dash/dash.go
=> dash: simplify construction of http.Client

cmd/miniooni/main.go, experiment/dash/dash.go, experiment/handler/handler.go, experiment/ndt7/ndt7.go, go.mod, go.sum, internal/humanizex/humanizex.go, internal/humanizex/humanizex_test.go
=> Make the output of DASH and NDT more pleasant

netx/httptransport/fake_test.go, netx/httptransport/httptransport.go, netx/httptransport/saver.go, netx/httptransport/saver_test.go, netx/trace/event.go
This is part of https://github.com/ooni/probe-engine/issues/543
=> More netx/httptransport refactoring

DomainCheck.bash
IDK if it's useful :man_shrugging:
=> check if jq is installed

cmd/miniooni/main.go
=> miniooni: also accept boolean options

netx/httptransport/fake_test.go, netx/httptransport/httptransport.go, netx/httptransport/httptransport_test.go
=> netx/httptransport: make construction more flexible

netx/httptransport/httptransport.go, netx/httptransport/httptransport_test.go, netx/httptransport/integration_test.go, netx/resolver/bogon.go, netx/resolver/bogon_test.go
Part of https://github.com/ooni/probe-engine/issues/547
=> netx: make sure we log addresses that trigger bogon filter

experiment/urlgetter/configurer.go, experiment/urlgetter/configurer_test.go, experiment/urlgetter/urlgetter.go
=> urlgetter/dnscache: allow multiple entries per domain

experiment_test.go, go.mod, go.sum, internal/mockable/mockable.go, internal/psiphonx/psiphonx.go, internal/psiphonx/psiphonx_test.go, internal/sessiontunnel/sessiontunnel.go, internal/sessiontunnel/sessiontunnel_test.go, internal/torx/torx.go, internal/torx/torx_internal_test.go, internal/torx/torx_test.go, libminiooni/libminiooni.go, model/model.go, session.go, session_test.go
Closes https://github.com/ooni/probe-engine/issues/587
=> Implement the tor tunnel

go.mod, go.sum, netx/httptransport/httptransport.go, netx/httptransport/httptransport_test.go
Closes https://github.com/ooni/probe-engine/issues/335
=> netx: use gocertifi in new code

experiment/urlgetter/configurer.go, experiment/urlgetter/configurer_test.go, netx/httptransport/httptransport.go, netx/httptransport/httptransport_test.go
This allows me to use this client also in other places and specifically
I am planning on using it in probeservices.
Part of https://github.com/ooni/probe/issues/887.
=> netx: factor DNSClient out of urlgetter

experiment.go, probeservices/bouncer.go, probeservices/client.go, probeservices/client_test.go, session.go, session_test.go
Part of https://github.com/ooni/probe/issues/887.
Close https://github.com/ooni/probe-engine/issues/19.
=> probeservices: implement fallback to cloudfronting

experiment.go, probeservices/client.go, probeservices/client_test.go, session.go
Closes https://github.com/ooni/probe-engine/issues/608
=> probeservices: sort http, then cloudfront, then onion

experiment/urlgetter/configurer.go, experiment/urlgetter/configurer_test.go, experiment/urlgetter/urlgetter.go
Closes https://github.com/ooni/probe-engine/issues/624
=> urlgetter: allow to choose specific TLS version

libminiooni/libminiooni.go
Part of https://github.com/ooni/probe-engine/issues/621
=> libminiooni: stop using --{bouncer,collector}-base-url

oonimkall/runner.go, oonimkall/runner_test.go, oonimkall/settings.go, probeservices/client.go
See https://github.com/ooni/probe-engine/issues/621
=> Finish migrating to OONI Probe Services

libminiooni/libminiooni.go, session.go, session_test.go
Part of https://github.com/ooni/probe/issues/886
=> Fix --proxy and use more precise user agent

experiment/stunreachability/stunreachability.go
Related to https://github.com/ooni/probe/issues/1185
=> stunreachability.go: inform the user about what we're doing

experiment/telegram/telegram.go, experiment/telegram/telegram_test.go
Part of https://github.com/ooni/probe-engine/issues/646
=> telegram: rewrite using experiment/urlgetter

internal/mockable/mockable.go, internal/orchestra/common_test.go, internal/orchestra/login.go, internal/orchestra/login_test.go, internal/orchestra/metadata.go, internal/orchestra/metadata_test.go, internal/orchestra/orchestra.go, internal/orchestra/orchestra_test.go, internal/orchestra/psiphon.go, internal/orchestra/psiphon_test.go, internal/orchestra/register.go, internal/orchestra/register_test.go, internal/orchestra/statefile.go, internal/orchestra/statefile_test.go, internal/orchestra/testlists/psiphon/psiphon_test.go, internal/orchestra/testlists/tor/tor_test.go, internal/orchestra/testorchestra/testorchestra.go, internal/orchestra/tor.go, internal/orchestra/tor_test.go, internal/orchestra/update.go, internal/orchestra/update_test.go, internal/orchestra/urls.go, internal/orchestra/urls_test.go, model/model.go, probeservices/client.go, session.go, session_test.go, testlists.go
=> orchestra: refactor to simplify using probe-services

geoiplookup/iplookup/avast/avast.go, geoiplookup/iplookup/ubuntu/ubuntu.go, internal/httpx/fetch_test.go, internal/httpx/jsonapi_test.go, internal/orchestra/login.go, internal/orchestra/psiphon.go, internal/orchestra/register.go, internal/orchestra/tor.go, internal/orchestra/update.go, internal/orchestra/urls.go, internal/resources/resources.go, internal/resources/resources_test.go
Spotted while working on 0aa9a5e.
Part of #651.
=> httpx, resources: improve testing and code quality

internal/orchestra/login.go, internal/orchestra/orchestra.go, internal/orchestra/register.go
=> orchestra: simplify Client by embedding httpx.Client

session.go
This allows us to use, in principle, also cloud fronted probe services
when there is need to do that. However, I've seen two issues:
1. https://github.com/ooni/backend/issues/431
2. https://github.com/ooni/backend/issues/430
Yet, at least we have made progress in that the usage of the probe
service for orchestra APIs is consistent with bouncer and collector
APIs. This will also soon allow choosing the fastest data centre.
=> NewOrchestraClient: use already selected probe service

probeservices/orchestra.go, probeservices/register.go
=> refactor(probeservices): move randomPassword in register.go

probeservices/collector.go
1. use names from which it's more clear the file stuff belongs to
2. use error variables rather than defining error inlines (this should
be very helpful to make testing more robust)
=> refactor(probeservices/collector.go): better names, error variables

probeservices/bouncer_test.go, probeservices/collector.go, probeservices/collector_test.go, probeservices/login.go, probeservices/login_test.go, probeservices/metadata_test.go, probeservices/probeservices.go, probeservices/psiphon.go, probeservices/psiphon_test.go, probeservices/register.go, probeservices/register_test.go, probeservices/statefile.go, probeservices/tor.go, probeservices/tor_test.go, session.go
Make sure everything easy I think we should do to improve the code
quality is either done right away or documented.
I think one-two more diffs are required to finish this work that
is related to https://github.com/ooni/probe-engine/issues/651.
=> codereview(probeservices): simple changes and TODO annotations

probeservices/collector.go, probeservices/collector_test.go, probeservices/login.go, probeservices/probeservices.go, probeservices/probeservices_test.go, probeservices/psiphon.go, probeservices/psiphon_test.go, probeservices/register.go, probeservices/register_test.go, probeservices/tor.go
Addresses the TODO mentioned in 4c0aaa591c335209836efc196c23c7310b87c812
=> probeservices: improve tests, increase coverage

session.go, session_test.go
It was reduced a bit when working on https://github.com/ooni/probe-engine/issues/651
=> session: ensure we have complete code coverage

experiment/tor/tor.go, experiment/tor/tor_test.go, model/model.go
Part of https://github.com/ooni/probe-engine/issues/643
=> tor: scrub private bridge addresses

internal/resources/assets.go, netx/archival/archival_test.go
=> Update to ooni/probe-assets@20200619115947

oonimkall/runner_test.go, probeservices/probeservices.go, probeservices/probeservices_test.go, probeservices/urls_test.go, testlists.go
While there, improve the quality of tests using probe services.
Part of https://github.com/ooni/probe-engine/issues/728
=> probeservices: use ps{1,2}.ooni.io

experiment/stunreachability/stunreachability_test.go, experiment/telegram/telegram.go, experiment/telegram/telegram_test.go, experiment/tor/tor_test.go, experiment/urlgetter/getter.go, experiment/urlgetter/multi.go, experiment/urlgetter/multi_test.go, experiment/urlgetter/runner_test.go, experiment/whatsapp/whatsapp.go, experiment/whatsapp/whatsapp_test.go, internal/oonitemplates/oonitemplates_test.go, netx/errorx/errorx.go, netx/errorx/errorx_test.go, oonimkall/runner.go
Part of https://github.com/ooni/probe-engine/issues/55
=> whatsapp: Go rewrite

experiment.go, experiment/urlgetter/runner.go, experiment/urlgetter/runner_test.go, experiment/urlgetter/urlgetter.go
Part of https://github.com/ooni/probe-engine/issues/55
While there, self identify correctly
=> whatsapp: instruments to investigate suspect MITM detection

experiment/internal/httpfailure/httpfailure.go, experiment/urlgetter/getter.go, experiment/urlgetter/getter_test.go, experiment/urlgetter/urlgetter.go, experiment/whatsapp/whatsapp.go, experiment/whatsapp/whatsapp_test.go, netx/archival/archival.go, netx/archival/archival_test.go
See https://github.com/ooni/probe-engine/issues/740
=> whatsapp: less strict checks for the web interface

experiment/whatsapp/whatsapp.go, experiment/whatsapp/whatsapp_test.go
1. remove the AllEndpoints option, which was basically increasing the
probability of detecting false positives
2. make sure we report the blocked WhatsApp endpoints (a concept
different from a TCP endpoint) like the spec says
Part of https://github.com/ooni/probe-engine/issues/743
=> whatsapp: make sure we don't violate v2020-07-09-001 of the spec

oonimkall/runner.go, oonimkall/runner_test.go, oonimkall/settings.go
Part of https://github.com/ooni/probe-engine/issues/743#issuecomment-656145345
While there, make the corresponding unit test much more precise
=> oonimkall: make AllEndpoints presence non fatal

probeservices/urls.go
Closes https://github.com/ooni/probe-engine/issues/754
=> fix(probeservices): use correct parameter for orchestra

experiment/fbmessenger/fbmessenger.go, experiment/fbmessenger/fbmessenger_test.go, internal/resources/resources_test.go
This is the initial rewrite. Maybe we'll need to do some more
work here to further refine the code in the next days.
This is part of https://github.com/ooni/probe-engine/issues/736.
=> fbmessenger: rewrite in Go

experiment/urlgetter/configurer_test.go, go.sum, internal/sessionresolver/sessionresolver.go, netx/httptransport/httptransport.go, netx/httptransport/httptransport_test.go, netx/resolver/dnsoverhttps_test.go, netx/resolver/integration_test.go, netx/resolver_test.go
Because Powerdns is better in terms of GDPR!
(I tried to make changes in some places in a fair way. I don't know if I did too much or too little!)
Closes #759
=> use Powerdns as default DoH

experiment/hirl/fake_test.go, experiment/hirl/hirl.go, experiment/hirl/hirl_test.go, internal/randx/randx.go, internal/randx/randx_test.go, probeservices/register.go
Part of https://github.com/ooni/probe-engine/issues/761
=> experiment: rewrite HIRL in Go

internal/randx/randx.go, internal/randx/randx_test.go, netx/selfcensor/selfcensor.go
Part of https://github.com/ooni/probe-engine/issues/763
=> randx: add support for changing string capitalisation

netx/resolver/dnsoverhttps.go
=> add overall timeout to DoH

cmd/miniooni/main.go, experiment/hhfm/fake_test.go, experiment/hhfm/hhfm.go, experiment/hhfm/hhfm_test.go, netx/modelx/modelx.go
Part of https://github.com/ooni/probe-engine/issues/763
=> Rewrite HHFM in Golang

experiment/webconnectivity/control.go, experiment/webconnectivity/control_test.go, experiment/webconnectivity/webconnectivity_test.go
=> experiment/webconnectivity: make sure code is tested

experiment/webconnectivity/analyze.go, experiment/webconnectivity/measure.go, experiment/webconnectivity/measure_test.go, experiment/webconnectivity/webconnectivity.go, experiment/webconnectivity/webconnectivity_test.go
1. make sure we define all the fields we should define
2. fill {HTTP,DNS}ExperimentFailure
3. make sure new code is fully tested
=> webconnectivity: start implementing analysis

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go, experiment/webconnectivity/webconnectivity.go
Based on https://github.com/measurement-kit/measurement-kit/blob/1166b57b9655a3e43cc41d5a73666651de594e28/src/libmeasurement_kit/ooni/web_connectivity.cpp#L142
=> webconnectivity/analysis: implement DNSConsistency

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
The algorithm is like https://github.com/measurement-kit/measurement-kit/blob/1166b57b9655a3e43cc41d5a73666651de594e28/src/libmeasurement_kit/ooni/web_connectivity.cpp#L228
We don't store the analysis result inside the measurement as
explained in detail in the diff.
=> webconnectivity/analysis: implement BlockedEndpoints

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
See https://github.com/measurement-kit/measurement-kit/blob/1166b57b9655a3e43cc41d5a73666651de594e28/src/libmeasurement_kit/ooni/web_connectivity.cpp#L55
=> webconnectivity/analysis: implement BodyLengthChecks

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
See https://github.com/measurement-kit/measurement-kit/blob/1166b57b9655a3e43cc41d5a73666651de594e28/src/libmeasurement_kit/ooni/web_connectivity.cpp#L60
=> webconnectivity/analysis: implement StatusCodeMatch

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
See https://github.com/measurement-kit/measurement-kit/blob/1166b57b9655a3e43cc41d5a73666651de594e28/src/libmeasurement_kit/ooni/web_connectivity.cpp#L71
=> webconnectivity/analyze: implement HeadersMatch

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
As documented in the code, this implementation might be slightly less
sensitive to false positives than MK's one.
=> webconnectivity/analyze: implement TitleMatch

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go
=> webconnectivity/analyze: define vars for consistent and inconsistent

experiment/webconnectivity/webconnectivity.go
=> webconnectivity: do not expose control request

experiment/webconnectivity/dnslookup.go, experiment/webconnectivity/dnslookup_test.go, experiment/webconnectivity/webconnectivity.go
Ex-post analysis of everything becomes too tricky.
=> webconnectivity: start breaking up Measure in smaller steps

experiment/webconnectivity/analyze.go, experiment/webconnectivity/analyze_test.go, experiment/webconnectivity/control.go, experiment/webconnectivity/dnsanalysis.go, experiment/webconnectivity/dnsanalysis_test.go, experiment/webconnectivity/dnslookup.go, experiment/webconnectivity/webconnectivity.go, experiment/webconnectivity/webconnectivity_test.go
=> webconnectivity: refactor DNS analysis in a separate file

experiment/webconnectivity/connects.go, experiment/webconnectivity/connects_test.go, experiment/webconnectivity/endpoints.go, experiment/webconnectivity/endpoints_test.go, experiment/webconnectivity/webconnectivity.go, experiment/whatsapp/whatsapp_test.go
=> webconnectivity: connect to all possible endpoints

experiment/webconnectivity/httpget.go, experiment/webconnectivity/httpget_test.go, experiment/webconnectivity/webconnectivity.go
=> webconnectivity: write separate HTTPGet step

experiment/webconnectivity/httpanalysis.go, experiment/webconnectivity/httpanalysis_test.go, experiment/webconnectivity/webconnectivity.go
1. always make keys lowercase
2. properly implement uncommon intersection
3. handle case when they are equal
4. add real world test cases
=> fix(webconnectivity): make sure headers check works

experiment/webconnectivity/control.go, experiment/webconnectivity/control_test.go
=> webconnectivity: remove unused function

experiment/hhfm/hhfm.go, experiment/hhfm/hhfm_test.go, experiment/hirl/hirl.go
Closes https://github.com/ooni/probe-engine/issues/821
=> hhfm, hirl: improve the output emitted during the experiment run

cmd/jafar/Dockerfile, cmd/jafar/README.md
This is part of https://github.com/ooni/probe-engine/issues/356.
I have only lightly edited the README.md file to reflect the fact that
this is a subdirectory rather than a standalone project.
=> cmd/jafar: adapt README.md and Dockerfile from original repo

.github/workflows/qa.yml, .gitignore, QA/README.md, QA/docker/start.bash, QA/docker/telegram.sh, QA/telegram/telegram.py, experiment/telegram/telegram.go
Part of https://github.com/ooni/probe-engine/issues/356
=> .github/workflows: integrate Jafar QA checks

.github/workflows/qa.yml, .gitignore, QA/README.md, QA/common.py, QA/pyrun.sh, QA/rundocker.bash, QA/telegram.py, QA/whatsapp.py, cmd/jafar/main.go
Part of https://github.com/ooni/probe-engine/issues/829
=> QA: implement whatsapp checks

.github/workflows/qa.yml, .gitignore, QA/fbmessenger.py, cmd/jafar/main.go, cmd/jafar/tlsproxy/tlsproxy.go
Part of https://github.com/ooni/probe-engine/issues/829
=> QA: write script for fbmessenger

.github/workflows/qa.yml, .gitignore, QA/common.py, QA/hhfm.py, QA/hirl.py
Part of https://github.com/ooni/probe-engine/issues/829
=> QA: add tests for hhfm and hirl

QA/common.py, QA/minioonilike.py
This will be very helpful for https://github.com/ooni/probe-engine/issues/810.
It will allow us, in fact, to compare the result obtained by MK to the one
obtained by miniooni in specific censorship conditions.
=> QA: add support for running measurement_kit

QA/webconnectivity.py
This is a rather common blocking case. Let us make sure we
measure this case with OPE like we do with MK.
I needed to remove the checks pertaining to the in depth
structure of the JSON, because fields are missing in JSON
files generated by MK. We know these bugs.
=> QA/webconnectivity: blocked IP w/ consistent DNS

QA/webconnectivity.py
=> QA/webconnectivity: DNS failure in the redirect chain

QA/webconnectivity.py
=> QA/webconnectivity: HTTP reset w/ inconsistent DNS

QA/Dockerfile, QA/webconnectivity.py
=> QA/webconnectivity.py: HTTP measurement ok, control failure

QA/webconnectivity.py
=> QA/webconnectivity: HTTPS okay but control failure

experiment/webconnectivity/summary.go
Discovered when smoke testing v3.0.7-beta.
=> fix(webconnectivity/summary): logging: add missing colon

.gitignore, CONTRIBUTING.md, README.md
Mostly minor changes and clarifications.
Part of https://github.com/ooni/probe-engine/issues/746.
=> CONTRIBUTING.md README.md: updates during documentation sprint

oonimkall/task.go, oonimkall/task_internal_test.go, oonimkall/tasks/chanlogger.go, oonimkall/tasks/event.go, oonimkall/tasks/eventemitter.go, oonimkall/tasks/eventemitter_test.go, oonimkall/tasks/runner.go, oonimkall/tasks/runner_test.go, oonimkall/tasks/settings.go
Yak shaving before working on https://github.com/ooni/probe-engine/issues/893.
Just following the boy scout rule here.
=> oonimkall: restructure package to improve testability

experiment.go, oonimkall/session.go, oonimkall/session_test.go, session.go
Part of https://github.com/ooni/probe-engine/issues/893
=> oonimkall: add support for session and geolocation

probeservices/collector.go, probeservices/collector_test.go
Part of https://github.com/ooni/probe-engine/issues/893
=> probeservices: add NewReportTemplate constructor

oonimkall/session.go, oonimkall/session_test.go
This PR contains the changes listed at https://github.com/ooni/probe-engine/issues/893#issuecomment-685688006. These changes were deemed necessary after integrating an experimental version of the codebase with OONI for Android (see https://github.com/ooni/probe-android/pull/358 and specifically https://github.com/ooni/probe-android/pull/358/commits/251dfb58ef698d8cae097dc89becc305e3367adc)
=> oonimkall/session.go: changes after Android integration experiment

oonimkall/session.go, oonimkall/session_internal_test.go, oonimkall/session_test.go, oonimkall/sessioncontext.go, oonimkall/sessioncontext_test.go, oonimkall/sessionlogger.go, oonimkall/sessionlogger_test.go, oonimkall/task.go
See https://github.com/ooni/probe-engine/issues/893#issuecomment-689031449 for
context on why we needed to rewrite the API.
=> oonimkall: implement session API v3

netx/resolver/integration_test.go
Further study:
https://developer.mozilla.org/en-US/docs/Mozilla/Internationalized_domain_names_support_in_Mozilla
https://docs.microsoft.com/en-us/windows/win32/intl/handling-internationalized-domain-names--idns
=> Ensuring we can handle IDNs without issues

libminiooni/libminiooni.go, libminiooni/libminiooni_unit_test.go
=> libminiooni: allow inputs from file

netx/netx.go, netx/netx_test.go, netx/resolver/idna.go, netx/resolver/idna_test.go, netx/resolver/integration_test.go, oonimkall/task_test.go
This is https://github.com/ooni/probe-engine/pull/943 plus an extra patch from me.
=> resolver: handle i18n domain names

oonimkall/session.go, oonimkall/session_test.go, session.go, session_internal_test.go, session_test.go
See https://github.com/ooni/probe-engine/issues/951#issuecomment-700625131
=> oonimkall: expose method to update resources

oonimkall/task_test.go
See https://github.com/ooni/probe-engine/issues/992#issuecomment-715079682.
=> fix(oonimkall): disable currently broken test

experiment/dnscheck/dnscheck.go, netx/netx.go, netx/netx_test.go
=> netx: improve and fix DNS issues

README.md, oonimkall/task_integration_test.go, session_integration_test.go
See https://github.com/ooni/probe-engine/issues/1005
=> doc: explain effect of #1005 on some tests

allexperiments.go, experiment/httphostheader/httphostheader.go, experiment/httphostheader/httphostheader_test.go, model/experiment.go
http host experiment. 
Towards #953
=> Http host based blocking experiment

experiment/fbmessenger/fbmessenger_test.go, experiment/hhfm/hhfm_test.go, experiment/webconnectivity/webconnectivity_test.go, internal/mockable/mockable.go, oonimkall/session_integration_test.go, probeservices/probeservices_test.go, probeservices/urls_test.go, session_integration_test.go
See https://github.com/ooni/backend/issues/461
=> chore: start using ams-pg-test.ooni.org for testing

libminiooni/README.md, libminiooni/libminiooni.go, oonimkall/tasks/runner.go
See https://github.com/ooni/probe/issues/1261
While there, remove stale statements from documentation.
=> fix(oonimkall): emit progress for tests with input

geolocate/iplookup.go, internal/multierror/multierror.go, internal/multierror/multierror_test.go, oonimkall/session_integration_test.go, session_integration_test.go
See https://github.com/ooni/probe-engine/issues/1026
=> fix(geolocate): do not hide underlying errors

geolocate/fake_test.go, geolocate/ipconfig.go, geolocate/ipinfo.go, geolocate/iplookup.go, geolocate/iplookup_integration_test.go, geolocate/iplookup_test.go, geolocate/mmdblookup_test.go, geolocate/stun.go, geolocate/stun_test.go, geolocate/ubuntu_test.go, internal/httpheader/useragent.go, internal/httpx/jsonapi.go, internal/httpx/jsonapi_test.go
This work is part of https://github.com/ooni/probe-engine/issues/1026
=> feature(geolocate): add more geolocate options

allexperiments.go, experiment/tlstool/internal/fake_test.go, experiment/tlstool/internal/split.go, experiment/tlstool/internal/split_test.go, experiment/tlstool/tlstool.go, experiment/tlstool/tlstool_test.go
First exploratory step towards https://github.com/ooni/probe-engine/issues/622.
=> feature(tlstool): very rough tool to experiment with SNI splitting

geolocate/iplookup.go, geolocate/iplookup_test.go
This closes https://github.com/ooni/probe-engine/issues/1026#issuecomment-724886213
=> fix(geolocate): better invalid-returned-ip error

oonimkall/tasks/runner.go
See https://github.com/ooni/probe/issues/1261
=> fix(oonimkall): better progress with max_runtime

geolocate/stun.go, geolocate/stun_test.go
See https://github.com/ooni/probe-engine/issues/1001#issuecomment-728952490
=> fix(geolocate/stun): better using default RTO

experiment/hhfm/hhfm_test.go, experiment/hirl/hirl.go, experiment/hirl/hirl_test.go
While there, fix a bunch of warnings in tests.
=> feat(hirl): continue introducing api required by probe-cli

experiment/ndt7/ndt7.go, experiment/ndt7/ndt7_test.go, experiment/riseupvpn/riseupvpn.go
While there, fix formatting in riseupvpn.
=> feat(ndt7): continue introducing api required by probe-cli

experiment/psiphon/psiphon.go, experiment/psiphon/psiphon_test.go
=> feat(psiphon): continue introducing api required by probe-cli

experiment/telegram/telegram.go, experiment/telegram/telegram_test.go
=> feat(telegram): continue introducing api required by probe-cli

experiment/tor/tor.go, experiment/tor/tor_test.go
=> feat(tor): continue introducing api required by probe-cli

experiment/webconnectivity/webconnectivity.go, experiment/webconnectivity/webconnectivity_test.go
=> feat(webconnectivity): continue introducing api required by probe-cli

experiment/whatsapp/whatsapp.go, experiment/whatsapp/whatsapp_test.go
=> feat(whatsapp): continue introducing api required by probe-cli

experiment/dash/dash_test.go, experiment/dnscheck/dnscheck_test.go, experiment/example/example_test.go, experiment/fbmessenger/fbmessenger_test.go, experiment/hhfm/hhfm_test.go, experiment/hirl/hirl_test.go, experiment/httphostheader/httphostheader_test.go, experiment/ndt7/ndt7_test.go, experiment/psiphon/psiphon.go, experiment/psiphon/psiphon_test.go, experiment/sniblocking/sniblocking_test.go, experiment/stunreachability/stunreachability_test.go, experiment/telegram/telegram_test.go, experiment/tlstool/tlstool_test.go, experiment/tor/tor_test.go, experiment/urlgetter/urlgetter_test.go, experiment/webconnectivity/webconnectivity_test.go, experiment/whatsapp/whatsapp_test.go, experiment_integration_test.go, model/experiment.go
Part of https://github.com/ooni/probe/issues/1283.
=> fix(experiment): improve tests around new api for probe-cli

experiment.go, session.go, session_internal_test.go
This work will help with https://github.com/ooni/probe/issues/1283.
=> experiment, session: expose more context based operations

model/measurement.go, model/model_test.go, model/privacysettings.go
As noted in https://github.com/ooni/probe-engine/issues/974
=> feat(model): improve tests implementation quality

model/scrub.go
Part of https://github.com/ooni/probe-engine/issues/974
=> cleanup: rename privacysettings.go to scrub.go

experiment/riseupvpn/riseupvpn.go, experiment/riseupvpn/riseupvpn_test.go
Part of https://github.com/ooni/probe-engine/issues/1060.
Code adapted from https://github.com/ooni/probe-cli/pull/171.
=> feat(riseupvpn): fill test keys

version/version.go
See https://github.com/ooni/probe-engine/issues/1043
=> chore: we're now hacking 0.22.0-alpha

libooniffi/testdata/webconnectivity.json
Part of https://github.com/ooni/probe-engine/issues/1043
=> fix(libooniffi): make sure smoke test runs

experiment/dnscheck/dnscheck.go, experiment/dnscheck/dnscheck_test.go
Part of https://github.com/ooni/probe-engine/issues/1115
=> feat(dnscheck): allow to override host and sni

experiment/dnscheck/dnscheck.go, experiment/dnscheck/dnscheck_test.go
This is still part of https://github.com/ooni/probe-engine/issues/1115
=> feat(dnscheck): record experiment settings

experiment/dnscheck/dnscheck.go, experiment/dnscheck/dnscheck_test.go, experiment/run/run.go, experiment/run/run_test.go
Working on https://github.com/ooni/probe-engine/issues/1115.
=> feat(dnscheck): addresses for domain and annotations

.gitignore, cmd/apitool/README.md, cmd/apitool/main.go, cmd/apitool/main_test.go, probeservices/checkreportid.go, probeservices/checkreportid_test.go, probeservices/measurementmeta.go, probeservices/measurementmeta_test.go, probeservices/urls.go, probeservices/urls_test.go
See https://github.com/ooni/probe-engine/issues/948.
Needed by mobile apps. It occurred to me this was "easy" to do
while trying to close on https://github.com/ooni/e2etesting/pull/28.
=> feat: API for fetching/checking measurements

probeservices/collector.go, probeservices/collector_test.go
This is very simple: only set the report ID field to measurements
we were able to submit successfully.
For all other measurements, it's actually also a conceptual mistake
to indicate a report ID, since they weren't submitted.
Occurred to me while reasoning on how to more effectively know
what wasn't submitted in https://github.com/ooni/probe-engine/issues/1115.
=> [BEHAVIOR CHANGE] fix(collector): make unsubmitted measurements

experiment/dnscheck/dnscheck.go, experiment/dnscheck/dnscheck_test.go, experiment/tlstool/tlstool.go, experiment/urlgetter/configurer.go, experiment/urlgetter/configurer_test.go, experiment/urlgetter/urlgetter.go, internal/sessionresolver/sessionresolver.go, netx/netx.go, netx/netx_test.go
See https://github.com/ooni/probe-engine/issues/1162
=> fix(dnscheck): allow to force specific TLS version

libminiooni/libminiooni.go
See https://github.com/ooni/probe-engine/issues/1164.
=> feat(miniooni): allow to randomize inputs

.github/workflows/miniooni.yml, QA/minioonilike.py, cmd/miniooni/main.go, libminiooni/libminiooni.go, libminiooni/libminiooni_integration_test.go
See https://github.com/ooni/probe-engine/issues/1150
=>  fix(miniooni): add informed consent

libminiooni/libminiooni.go
Related to https://github.com/ooni/probe-cli/pull/187.
=> fix(libminiooni): don't leak an open file

locationlookup.go, locationlookup_test.go, model/locationinfo.go, session.go
Reference issue: https://github.com/ooni/probe-engine/issues/1174.
=> fix(session): much better code to lookup location

.github/workflows/android.yml, .github/workflows/ios.yml, build-android.bash
While there, ensure we build Android and iOS also in release
branches. So we notice issues _before_ releasing.
=> fix(android): pin ndk version and repair build

version/version.go
We're making progress towards the next release. Let us bless a new release candidate featuring QUIC improvements, an ndt7 fix that makes the code more correct, and support for 32 bit builds.
=> chore: tag v0.23.0-alpha.2
